import { ExternalLink, LoaderCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router';

import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface Row { workspacePublicId: number; workspaceName: string; workspaceType: string; workspaceStatus: string; customerPublicId: number | null; ownerUserPublicId: number | null; ownerName: string | null; ownerMobile: string | null; packageName: string | null; subscriptionStatus: string | null; termEndsAt: string | null }

/** Permission-gated customer/workspace/subscription administration list. */
export default function CustomersPage() {
	const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
	useEffect(() => { void authenticatedFetch('/api/v1/operations/customer-workspaces').then(async (response) => { const body = await response.json() as { data?: Row[]; message: string; status: boolean }; if (!response.ok || !body.status) throw new Error(body.message); setRows(body.data ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load customers.')).finally(() => setLoading(false)); }, []);
	return <section><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Commerce</p><h1 className="mt-2 text-4xl font-black">Customers and workspaces</h1><p className="mt-3 text-app-muted">Inspect ownership, primary hosting subscriptions, term state, and add-ons.</p>{error && <p className="mt-6 rounded-xl bg-rose-500/10 p-3 text-rose-600 dark:text-rose-300">{error}</p>}{loading ? <div className="grid min-h-56 place-items-center"><LoaderCircle className="size-6 animate-spin" /></div> : <div className="mt-8 overflow-x-auto rounded-3xl border border-brand-primary/10 bg-app-surface"><table className="w-full min-w-[64rem] text-left text-sm"><thead className="bg-brand-primary/5 text-xs uppercase tracking-wide text-app-muted"><tr><th className="px-5 py-4">Workspace</th><th className="px-5 py-4">Owner</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Term end</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-brand-primary/10">{rows.map((row) => <tr key={`${row.workspacePublicId}-${row.subscriptionStatus}`}><td className="px-5 py-4"><strong>{row.workspaceName}</strong><br /><span className="text-xs text-app-muted">#{row.workspacePublicId} · {row.workspaceType}</span></td><td className="px-5 py-4">{row.ownerName ?? 'Unassigned'}<br /><span className="text-xs text-app-muted">{row.ownerMobile ?? ''}</span></td><td className="px-5 py-4">{row.customerPublicId ? `#${row.customerPublicId}` : '—'}</td><td className="px-5 py-4">{row.packageName ?? 'None'}</td><td className="px-5 py-4 capitalize">{row.subscriptionStatus ?? row.workspaceStatus}</td><td className="px-5 py-4">{row.termEndsAt ? new Date(row.termEndsAt).toLocaleDateString() : '—'}</td><td className="px-5 py-4"><Link aria-label={`View ${row.workspaceName}`} className="inline-grid size-9 place-items-center rounded-lg border border-brand-primary/15" to={`/admin/customers/${row.workspacePublicId}`}><ExternalLink className="size-4" /></Link></td></tr>)}</tbody></table></div>}</section>;
}
