import { ArrowLeft, Clock3, Database, FileCode2, Github, Globe2, LoaderCircle, Rocket } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { toast } from 'sonner';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface Domain { hostname: string; id: string; isEnabled: boolean; isPrimary: boolean; status: string; tlsStatus: string; type: string }
interface Cron { command: string; frequency: string; id: string; isEnabled: boolean; name: string; syncStatus: string }
interface Deployment { completedAt: string | null; createdAt: string; failureReason: string | null; id: string; status: string }
interface DatabaseBinding { databaseId: string; databaseName: string; engine: string; engineVersion: string; status: string; username: string }
interface Application { baseDirectory: string; branch: string; createdAt: string; crons: Cron[]; databases: DatabaseBinding[]; deployments: Deployment[]; domains: Domain[]; environment: string; framework: string | null; id: string; name: string | null; port: number; provider: string | null; publicUrl: string | null; repository: string; stack: string; status: string | null; version: string }
interface DatabaseRow { connectionLimit: number | null; databaseName: string; engine: string; engineVersion: string; id: string; lastBackedUpAt: string | null; status: string; storageQuotaMb: number | null; username: string }
interface GitConnection { accountLogin: string; accountName: string | null; accountType: string; id: string; providerSyncError: string | null; providerSyncStatus: string; status: string }
interface Detail { applications: Application[]; databases: DatabaseRow[]; gitConnections: GitConnection[]; workspace: { name: string; publicId: number; status: string; type: string } }

export default function CustomerResourcesPage() {
	const { userId, workspaceId } = useParams(); const [detail, setDetail] = useState<Detail>();
	useEffect(() => { void authenticatedFetch(`/api/v1/operations/users/${userId}/workspaces/${workspaceId}`).then(async (response) => { const body = await response.json() as { data?: Detail; message: string; status: boolean }; if (!response.ok || !body.status || !body.data) throw new Error(body.message); setDetail(body.data); }).catch((error: unknown) => toast.error(error instanceof Error ? error.message : 'Unable to load workspace resources.')); }, [userId, workspaceId]);
	if (!detail) return <div className="grid min-h-64 place-items-center"><LoaderCircle className="size-6 animate-spin" /></div>;
	return <section><div className="flex flex-wrap items-center justify-between gap-3"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-brand-primary dark:text-brand-action" to={`/admin/customers/users/${userId}`}><ArrowLeft className="size-4" />User</Link><Link className="rounded-xl border border-brand-primary/15 px-4 py-2 text-sm font-bold" to={`/admin/customers/${workspaceId}`}>Billing controls</Link></div><h1 className="mt-5 text-4xl font-black">{detail.workspace.name}</h1><p className="mt-2 capitalize text-app-muted">Workspace #{detail.workspace.publicId} · {detail.workspace.type} · {detail.workspace.status}</p>
		<h2 className="mt-9 flex items-center gap-2 text-2xl font-black"><Rocket className="size-5" />Applications</h2><div className="mt-4 grid gap-5">{detail.applications.map((application) => <article className="rounded-3xl border border-brand-primary/10 bg-app-surface p-6" key={application.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-black">{application.name ?? application.id}</h3><p className="mt-1 text-sm text-app-muted">{application.framework ?? application.stack} · {application.stack} {application.version} · {application.environment}</p></div><span className="capitalize">{application.status ?? 'build only'}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4">{[['Repository', application.repository], ['Branch', application.branch], ['Project directory', application.baseDirectory], ['Port', application.port]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase text-app-muted">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl>
			<div className="mt-6 grid gap-4 lg:grid-cols-2"><ResourceBlock icon={<Globe2 className="size-4" />} title={`Domains (${application.domains.length})`}>{application.domains.map((domain) => <p key={domain.id}>{domain.hostname} · {domain.status} · TLS {domain.tlsStatus}{domain.isPrimary ? ' · primary' : ''}</p>)}</ResourceBlock><ResourceBlock icon={<Database className="size-4" />} title={`Databases (${application.databases.length})`}>{application.databases.map((database) => <p key={database.databaseId}>{database.databaseName} · {database.engine} {database.engineVersion} · {database.username}</p>)}</ResourceBlock><ResourceBlock icon={<Clock3 className="size-4" />} title={`Scheduled tasks (${application.crons.length})`}>{application.crons.map((cron) => <p key={cron.id}>{cron.name} · <code>{cron.frequency}</code> · {cron.isEnabled ? 'enabled' : 'disabled'}<br /><code className="text-xs text-app-muted">{cron.command}</code></p>)}</ResourceBlock><ResourceBlock icon={<Rocket className="size-4" />} title={`Deployments (${application.deployments.length})`}>{application.deployments.slice(0, 10).map((deployment) => <p key={deployment.id}>{deployment.status} · {new Date(deployment.createdAt).toLocaleString('en-IN')}{deployment.failureReason ? ` · ${deployment.failureReason}` : ''}</p>)}</ResourceBlock></div>
		</article>)}{!detail.applications.length && <p className="rounded-2xl border border-dashed border-brand-primary/20 p-6 text-app-muted">No applications visible with your assigned permissions.</p>}</div>
		<div className="mt-9 grid gap-6 lg:grid-cols-2"><section><h2 className="flex items-center gap-2 text-2xl font-black"><Github className="size-5" />Git connections</h2><div className="mt-4 grid gap-3">{detail.gitConnections.map((connection) => <article className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5" key={connection.id}><strong>{connection.accountName ?? connection.accountLogin}</strong><p className="mt-1 text-sm text-app-muted">@{connection.accountLogin} · {connection.accountType} · {connection.status}</p><p className="mt-2 text-sm">Provider sync: {connection.providerSyncStatus}{connection.providerSyncError ? ` · ${connection.providerSyncError}` : ''}</p></article>)}{!detail.gitConnections.length && <p className="text-app-muted">No visible Git connections.</p>}</div></section><section><h2 className="flex items-center gap-2 text-2xl font-black"><Database className="size-5" />Workspace databases</h2><div className="mt-4 grid gap-3">{detail.databases.map((database) => <article className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5" key={database.id}><strong>{database.databaseName}</strong><p className="mt-1 text-sm text-app-muted">{database.engine} {database.engineVersion} · {database.status}</p><p className="mt-2 text-sm">User: {database.username} · {database.connectionLimit ?? 'default'} connections · {database.storageQuotaMb ?? 'default'} MB</p></article>)}{!detail.databases.length && <p className="text-app-muted">No visible databases.</p>}</div></section></div>
		<h2 className="mt-9 flex items-center gap-2 text-2xl font-black"><FileCode2 className="size-5" />Source files</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{detail.applications.map((application) => <Link className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5 font-bold transition hover:border-brand-action" key={application.id} to={`/admin/customers/users/${userId}/workspaces/${workspaceId}/applications/${application.id}/files`}>{application.name ?? application.id}<span className="mt-1 block truncate text-xs font-normal text-app-muted">{application.repository}</span></Link>)}</div>
	</section>;
}

function ResourceBlock({ children, icon, title }: { children: React.ReactNode; icon: React.ReactNode; title: string }) { return <section className="rounded-2xl bg-app-bg p-4"><h4 className="flex items-center gap-2 font-bold">{icon}{title}</h4><div className="mt-3 grid gap-2 text-sm">{children || <p className="text-app-muted">None</p>}</div></section>; }
