import { ArrowLeft, Boxes as Workspace, KeyRound, LoaderCircle, LogOut, ShieldAlert } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router';
import { toast } from 'sonner';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface Session { activeContextType: string; browserName: string | null; deviceLabel: string | null; id: string; ipAddress: string | null; lastActiveAt: string; location: string | null; osName: string | null; revokedAt: string | null }
interface Event { createdAt: string; id: string; ipAddress: string | null; reason: string | null; status: string; type: string }
interface WorkspaceRow { packageName: string | null; role: string; subscriptionStatus: string | null; termEndsAt: string | null; workspaceName: string; workspacePublicId: number; workspaceStatus: string; workspaceType: string }
interface Detail { authentication?: Event[]; permissions: { canRevokeSessions: boolean; canSuspend: boolean }; sessions?: Session[]; user: { countryCode: string; createdAt: string; customerPublicId: number | null; displayName: string | null; mobile: string; mobileVerifiedAt: string | null; onboardingStatus: string | null; publicId: number; status: string }; workspaces: WorkspaceRow[] }
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as { data?: T; message: string; status: boolean }; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }

export default function CustomerUserPage() {
	const { userId } = useParams(); const [detail, setDetail] = useState<Detail>();
	async function load() { if (userId) setDetail(await api<Detail>(`/api/v1/operations/users/${userId}`)); }
	useEffect(() => { if (userId) void api<Detail>(`/api/v1/operations/users/${userId}`).then(setDetail).catch((error: unknown) => toast.error(error instanceof Error ? error.message : 'Unable to load user.')); }, [userId]);
	async function status(value: 'active' | 'inactive' | 'suspended') { const reason = window.prompt(`Reason for changing this user to ${value}:`); if (!reason) return; try { await api(`/api/v1/operations/users/${userId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ status: value, reason }) }); toast.success('User status updated.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Status update failed.'); } }
	async function revoke(session: Session) { const reason = window.prompt('Reason for revoking this session:'); if (!reason) return; try { await api(`/api/v1/operations/users/${userId}/sessions/${session.id}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ reason }) }); toast.success('Session revoked.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Session revocation failed.'); } }
	if (!detail) return <div className="grid min-h-64 place-items-center"><LoaderCircle className="size-6 animate-spin" /></div>;
	return <section><Link className="inline-flex items-center gap-2 text-sm font-semibold text-brand-primary dark:text-brand-action" to="/admin/customers"><ArrowLeft className="size-4" />Users</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-4xl font-black">{detail.user.displayName ?? 'Unnamed user'}</h1><p className="mt-2 text-app-muted">User #{detail.user.publicId} · {detail.user.countryCode}{detail.user.mobile} · <span className="capitalize">{detail.user.status}</span></p></div>{detail.permissions.canSuspend && <div className="flex flex-wrap gap-2">{(['active', 'inactive', 'suspended'] as const).map((value) => <button className="rounded-xl border border-brand-primary/15 px-4 py-2 font-bold capitalize disabled:opacity-40" disabled={detail.user.status === value} key={value} onClick={() => void status(value)} type="button">{value}</button>)}</div>}</div>
		<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Customer', detail.user.customerPublicId ? `#${detail.user.customerPublicId}` : 'Not created'], ['Onboarding', detail.user.onboardingStatus ?? '—'], ['Mobile', detail.user.mobileVerifiedAt ? 'Verified' : 'Unverified'], ['Registered', new Date(detail.user.createdAt).toLocaleDateString('en-IN')]].map(([label, value]) => <article className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5" key={label}><p className="text-xs font-bold uppercase text-app-muted">{label}</p><p className="mt-2 font-bold capitalize">{value}</p></article>)}</div>
		<h2 className="mt-9 flex items-center gap-2 text-2xl font-black"><Workspace className="size-5" />Workspaces</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{detail.workspaces.map((row) => <Link className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5 transition hover:border-brand-action" key={row.workspacePublicId} to={`/admin/customers/users/${userId}/workspaces/${row.workspacePublicId}`}><div className="flex justify-between gap-3"><strong>{row.workspaceName}</strong><span className="capitalize text-app-muted">{row.workspaceStatus}</span></div><p className="mt-2 text-sm text-app-muted">#{row.workspacePublicId} · {row.workspaceType} · {row.role}</p><p className="mt-3 text-sm">{row.packageName ?? 'No package'} · {row.subscriptionStatus ?? 'No subscription'}</p></Link>)}{!detail.workspaces.length && <p className="rounded-2xl border border-dashed border-brand-primary/20 p-6 text-app-muted">No workspaces.</p>}</div>
		{detail.sessions && <><h2 className="mt-9 flex items-center gap-2 text-2xl font-black"><KeyRound className="size-5" />Sessions</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-brand-primary/10 bg-app-surface"><table className="w-full min-w-[52rem] text-left text-sm"><thead className="bg-brand-primary/5 text-xs uppercase text-app-muted"><tr><th className="p-4">Device</th><th className="p-4">IP / location</th><th className="p-4">Context</th><th className="p-4">Last active</th><th className="p-4" /></tr></thead><tbody>{detail.sessions.map((session) => <tr className="border-t border-brand-primary/10" key={session.id}><td className="p-4">{session.deviceLabel ?? `${session.browserName ?? 'Browser'} on ${session.osName ?? 'unknown OS'}`}</td><td className="p-4">{session.ipAddress ?? '—'}<br /><span className="text-xs text-app-muted">{session.location ?? ''}</span></td><td className="p-4 capitalize">{session.activeContextType}</td><td className="p-4">{new Date(session.lastActiveAt).toLocaleString('en-IN')}</td><td className="p-4">{detail.permissions.canRevokeSessions && !session.revokedAt && <button aria-label="Revoke session" className="rounded-lg border border-red-500/20 p-2 text-red-600" onClick={() => void revoke(session)} type="button"><LogOut className="size-4" /></button>}</td></tr>)}</tbody></table></div></>}
		{detail.authentication && <><h2 className="mt-9 flex items-center gap-2 text-2xl font-black"><ShieldAlert className="size-5" />Authentication history</h2><div className="mt-4 grid gap-2">{detail.authentication.map((event) => <div className="rounded-xl border border-brand-primary/10 bg-app-surface p-4 text-sm" key={event.id}><strong className="capitalize">{event.type.replaceAll('_', ' ')}</strong> · <span className="capitalize">{event.status}</span><span className="float-right text-app-muted">{new Date(event.createdAt).toLocaleString('en-IN')}</span>{event.reason && <p className="mt-1 text-app-muted">{event.reason}</p>}</div>)}</div></>}
	</section>;
}
