import { ExternalLink, LoaderCircle, Search, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface Row { countryCode: string; createdAt: string; customerPublicId: number | null; displayName: string | null; lastActiveAt: string | null; mobile: string; mobileVerifiedAt: string | null; publicId: number; status: string; workspaceCount: number }

/** Audited user inventory leading into workspace and infrastructure control. */
export default function CustomersPage() {
	const [rows, setRows] = useState<Row[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
	useEffect(() => { void authenticatedFetch('/api/v1/operations/users').then(async (response) => { const body = await response.json() as { data?: Row[]; message: string; status: boolean }; if (!response.ok || !body.status) throw new Error(body.message); setRows(body.data ?? []); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load users.')).finally(() => setLoading(false)); }, []);
	const filtered = useMemo(() => rows.filter((row) => `${row.displayName} ${row.countryCode}${row.mobile} ${row.publicId} ${row.customerPublicId}`.toLowerCase().includes(query.toLowerCase())), [query, rows]);
	return <section><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Customer control</p><h1 className="mt-2 text-4xl font-black">Users</h1><p className="mt-3 text-app-muted">Inspect identities, sessions, workspaces, projects, Git, databases, domains, deployments, and scheduled tasks.</p><label className="mt-6 flex max-w-xl items-center gap-3 rounded-xl border border-brand-primary/15 bg-app-surface px-4 py-3"><Search className="size-4 text-app-muted" /><input className="min-w-0 flex-1 bg-transparent outline-none" onChange={(event) => setQuery(event.target.value)} placeholder="Search name, phone, user or customer ID" value={query} /></label>{error && <p className="mt-6 rounded-xl bg-rose-500/10 p-3 text-rose-600 dark:text-rose-300">{error}</p>}{loading ? <div className="grid min-h-56 place-items-center"><LoaderCircle className="size-6 animate-spin" /></div> : <div className="mt-7 overflow-x-auto rounded-3xl border border-brand-primary/10 bg-app-surface"><table className="w-full min-w-[58rem] text-left text-sm"><thead className="bg-brand-primary/5 text-xs uppercase text-app-muted"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Phone</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Workspaces</th><th className="px-5 py-4">Last active</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-brand-primary/10">{filtered.map((row) => <tr key={row.publicId}><td className="px-5 py-4"><span className="flex items-center gap-3"><UserRound className="size-5 text-app-muted" /><span><strong>{row.displayName ?? 'Unnamed user'}</strong><br /><span className="text-xs text-app-muted">User #{row.publicId}{row.customerPublicId ? ` · Customer #${row.customerPublicId}` : ''}</span></span></span></td><td className="px-5 py-4">{row.countryCode}{row.mobile}<br /><span className="text-xs text-app-muted">{row.mobileVerifiedAt ? 'Verified' : 'Unverified'}</span></td><td className="px-5 py-4 capitalize">{row.status}</td><td className="px-5 py-4">{Number(row.workspaceCount)}</td><td className="px-5 py-4">{row.lastActiveAt ? new Date(row.lastActiveAt).toLocaleString('en-IN') : 'Never'}</td><td className="px-5 py-4"><Link aria-label={`Control user ${row.publicId}`} className="inline-grid size-9 place-items-center rounded-lg border border-brand-primary/15" to={`/admin/customers/users/${row.publicId}`}><ExternalLink className="size-4" /></Link></td></tr>)}</tbody></table>{!filtered.length && <p className="p-8 text-center text-app-muted">No users match this search.</p>}</div>}</section>;
}
