import { relations, sql } from 'drizzle-orm';
import { index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';

import { workspaceSubscriptions } from './subscriptions';
import { workspaces } from './tenancy';

export const hostingProviderEnum = pgEnum('hosting_provider', ['mock', 'coolify']);
export const provisioningJobStatusEnum = pgEnum('provisioning_job_status', ['queued', 'processing', 'succeeded', 'failed', 'cancelled']);
export const workspaceResourceKindEnum = pgEnum('workspace_resource_kind', ['application', 'database', 'service']);
export const workspaceResourceStatusEnum = pgEnum('workspace_resource_status', ['provisioning', 'running', 'stopped', 'failed', 'unknown']);

export const provisioningJobs = pgTable('provisioning_jobs', {
	id: uuid('id').primaryKey().defaultRandom(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'restrict' }), subscriptionId: uuid('subscription_id').notNull().references(() => workspaceSubscriptions.id, { onDelete: 'restrict' }), provider: hostingProviderEnum('provider').notNull(), status: provisioningJobStatusEnum('status').notNull().default('queued'), idempotencyKey: varchar('idempotency_key', { length: 200 }).notNull(), attemptCount: integer('attempt_count').notNull().default(0), maximumAttempts: integer('maximum_attempts').notNull().default(5), nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(), lockedAt: timestamp('locked_at', { withTimezone: true }), completedAt: timestamp('completed_at', { withTimezone: true }), lastError: text('last_error'), input: jsonb('input').$type<Record<string, unknown>>().notNull().default({}), result: jsonb('result').$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('provisioning_jobs_idempotency_unique').on(table.idempotencyKey).where(sql`${table.deletedAt} IS NULL`), index('provisioning_jobs_runnable_idx').on(table.status, table.nextAttemptAt), index('provisioning_jobs_workspace_idx').on(table.workspaceId, table.createdAt)]);

export const workspaceResources = pgTable('workspace_resources', {
	id: uuid('id').primaryKey().defaultRandom(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'restrict' }), provisioningJobId: uuid('provisioning_job_id').references(() => provisioningJobs.id, { onDelete: 'restrict' }), provider: hostingProviderEnum('provider').notNull(), kind: workspaceResourceKindEnum('kind').notNull(), name: varchar('name', { length: 160 }).notNull(), providerResourceId: varchar('provider_resource_id', { length: 255 }).notNull(), providerDeploymentId: varchar('provider_deployment_id', { length: 255 }), status: workspaceResourceStatusEnum('status').notNull().default('provisioning'), publicUrl: varchar('public_url', { length: 500 }), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), lastReconciledAt: timestamp('last_reconciled_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('workspace_resources_provider_resource_unique').on(table.provider, table.providerResourceId).where(sql`${table.deletedAt} IS NULL`), index('workspace_resources_workspace_status_idx').on(table.workspaceId, table.status)]);

export const provisioningJobRelations = relations(provisioningJobs, ({ many, one }) => ({ workspace: one(workspaces, { fields: [provisioningJobs.workspaceId], references: [workspaces.id] }), subscription: one(workspaceSubscriptions, { fields: [provisioningJobs.subscriptionId], references: [workspaceSubscriptions.id] }), resources: many(workspaceResources) }));
export const workspaceResourceRelations = relations(workspaceResources, ({ one }) => ({ workspace: one(workspaces, { fields: [workspaceResources.workspaceId], references: [workspaces.id] }), job: one(provisioningJobs, { fields: [workspaceResources.provisioningJobId], references: [provisioningJobs.id] }) }));
