import { relations, sql } from 'drizzle-orm';
import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';

import { users } from './identity';
import { workspaceResources } from './provisioning';

export const providerConnectionStatusEnum = pgEnum('provider_connection_status', ['active', 'disabled', 'unhealthy']);
export const providerTokenStatusEnum = pgEnum('provider_token_status', ['active', 'retired', 'revoked']);
export const providerImportKindEnum = pgEnum('provider_import_kind', ['server', 'application', 'database', 'service', 'deployment']);
export const providerReconciliationStatusEnum = pgEnum('provider_reconciliation_status', ['running', 'succeeded', 'partial', 'failed']);

/** Database-managed Coolify endpoint and placement configuration; token material is versioned separately. */
export const providerConnections = pgTable('provider_connections', {
	id: uuid('id').primaryKey().defaultRandom(), code: varchar('code', { length: 120 }).notNull(), name: varchar('name', { length: 160 }).notNull(), provider: varchar('provider', { length: 40 }).notNull().default('coolify'), baseUrl: varchar('base_url', { length: 500 }).notNull(), teamId: integer('team_id'), serverUuid: varchar('server_uuid', { length: 120 }), destinationUuid: varchar('destination_uuid', { length: 120 }), defaultProjectUuid: varchar('default_project_uuid', { length: 120 }), defaultEnvironmentName: varchar('default_environment_name', { length: 120 }).notNull().default('production'), wildcardDomain: varchar('wildcard_domain', { length: 255 }), status: providerConnectionStatusEnum('status').notNull().default('active'), isDefault: boolean('is_default').notNull().default(false), lastValidatedAt: timestamp('last_validated_at', { withTimezone: true }), lastHealthyAt: timestamp('last_healthy_at', { withTimezone: true }), lastError: text('last_error'), createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'restrict' }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('provider_connections_code_unique').on(table.code).where(sql`${table.deletedAt} IS NULL`), uniqueIndex('provider_connections_default_unique').on(table.provider).where(sql`${table.isDefault} = true AND ${table.status} = 'active' AND ${table.deletedAt} IS NULL`), index('provider_connections_status_idx').on(table.provider, table.status)]);

/** Encrypted, fingerprinted token versions supporting non-destructive rotation and rollback. */
export const providerConnectionTokens = pgTable('provider_connection_tokens', {
	id: uuid('id').primaryKey().defaultRandom(), connectionId: uuid('connection_id').notNull().references(() => providerConnections.id, { onDelete: 'restrict' }), version: integer('version').notNull(), tokenCiphertext: text('token_ciphertext').notNull(), tokenFingerprint: varchar('token_fingerprint', { length: 64 }).notNull(), tokenSuffix: varchar('token_suffix', { length: 12 }).notNull(), status: providerTokenStatusEnum('status').notNull().default('active'), activatedAt: timestamp('activated_at', { withTimezone: true }).notNull().defaultNow(), retiredAt: timestamp('retired_at', { withTimezone: true }), createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'restrict' }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('provider_connection_tokens_version_unique').on(table.connectionId, table.version), uniqueIndex('provider_connection_tokens_active_unique').on(table.connectionId).where(sql`${table.status} = 'active' AND ${table.deletedAt} IS NULL`), index('provider_connection_tokens_fingerprint_idx').on(table.tokenFingerprint)]);

/** Provider state snapshot. It never creates commercial ownership automatically. */
export const providerImportedResources = pgTable('provider_imported_resources', {
	id: uuid('id').primaryKey().defaultRandom(), connectionId: uuid('connection_id').notNull().references(() => providerConnections.id, { onDelete: 'restrict' }), kind: providerImportKindEnum('kind').notNull(), providerResourceId: varchar('provider_resource_id', { length: 255 }).notNull(), name: varchar('name', { length: 255 }).notNull(), status: varchar('status', { length: 120 }), payloadHash: varchar('payload_hash', { length: 64 }).notNull(), snapshot: jsonb('snapshot').$type<Record<string, unknown>>().notNull(), matchedWorkspaceResourceId: uuid('matched_workspace_resource_id').references(() => workspaceResources.id, { onDelete: 'set null' }), firstObservedAt: timestamp('first_observed_at', { withTimezone: true }).notNull().defaultNow(), lastObservedAt: timestamp('last_observed_at', { withTimezone: true }).notNull().defaultNow(), missingSince: timestamp('missing_since', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('provider_imported_resources_identity_unique').on(table.connectionId, table.kind, table.providerResourceId).where(sql`${table.deletedAt} IS NULL`), index('provider_imported_resources_observed_idx').on(table.connectionId, table.kind, table.lastObservedAt), index('provider_imported_resources_match_idx').on(table.matchedWorkspaceResourceId)]);

export const providerReconciliationRuns = pgTable('provider_reconciliation_runs', {
	id: uuid('id').primaryKey().defaultRandom(), connectionId: uuid('connection_id').notNull().references(() => providerConnections.id, { onDelete: 'restrict' }), status: providerReconciliationStatusEnum('status').notNull().default('running'), importedCounts: jsonb('imported_counts').$type<Record<string, number>>().notNull().default({}), failureDetails: jsonb('failure_details').$type<Array<Record<string, unknown>>>().notNull().default([]), startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(), completedAt: timestamp('completed_at', { withTimezone: true }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [index('provider_reconciliation_runs_connection_idx').on(table.connectionId, table.startedAt)]);

export const providerConnectionRelations = relations(providerConnections, ({ many }) => ({ tokens: many(providerConnectionTokens), imports: many(providerImportedResources), runs: many(providerReconciliationRuns) }));
export const providerTokenRelations = relations(providerConnectionTokens, ({ one }) => ({ connection: one(providerConnections, { fields: [providerConnectionTokens.connectionId], references: [providerConnections.id] }) }));
export const providerImportRelations = relations(providerImportedResources, ({ one }) => ({ connection: one(providerConnections, { fields: [providerImportedResources.connectionId], references: [providerConnections.id] }), matchedResource: one(workspaceResources, { fields: [providerImportedResources.matchedWorkspaceResourceId], references: [workspaceResources.id] }) }));
export const providerReconciliationRelations = relations(providerReconciliationRuns, ({ one }) => ({ connection: one(providerConnections, { fields: [providerReconciliationRuns.connectionId], references: [providerConnections.id] }) }));
