import { relations, sql } from 'drizzle-orm';
import { bigint, boolean, check, index, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';

import { users } from './identity';
import { workspaceSubscriptions } from './subscriptions';
import { workspaces } from './tenancy';

export const usageReservationStatusEnum = pgEnum('usage_reservation_status', ['pending', 'committed', 'released', 'expired']);
export const usageObservationStatusEnum = pgEnum('usage_observation_status', ['fresh', 'stale', 'unavailable']);

/** Short-lived transactional claim that closes count-quota races before resource creation. */
export const workspaceUsageReservations = pgTable('workspace_usage_reservations', {
	id: uuid('id').primaryKey().defaultRandom(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'restrict' }), subscriptionId: uuid('subscription_id').references(() => workspaceSubscriptions.id, { onDelete: 'restrict' }), entitlementCode: varchar('entitlement_code', { length: 120 }).notNull(), quantity: bigint('quantity', { mode: 'number' }).notNull(), idempotencyKey: varchar('idempotency_key', { length: 200 }).notNull(), status: usageReservationStatusEnum('status').notNull().default('pending'), resourceType: varchar('resource_type', { length: 80 }), resourceId: uuid('resource_id'), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), committedAt: timestamp('committed_at', { withTimezone: true }), releasedAt: timestamp('released_at', { withTimezone: true }), releaseReason: varchar('release_reason', { length: 500 }), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('workspace_usage_reservations_idempotency_unique').on(table.workspaceId, table.idempotencyKey).where(sql`${table.deletedAt} IS NULL`), index('workspace_usage_reservations_pending_idx').on(table.workspaceId, table.entitlementCode, table.status, table.expiresAt), check('workspace_usage_reservations_quantity_check', sql`${table.quantity} > 0`)]);

/** Timestamped provider or internal measurement with explicit freshness. */
export const workspaceUsageObservations = pgTable('workspace_usage_observations', {
	id: uuid('id').primaryKey().defaultRandom(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'restrict' }), entitlementCode: varchar('entitlement_code', { length: 120 }).notNull(), value: bigint('value', { mode: 'number' }).notNull(), unit: varchar('unit', { length: 60 }), source: varchar('source', { length: 80 }).notNull(), status: usageObservationStatusEnum('status').notNull().default('fresh'), periodStart: timestamp('period_start', { withTimezone: true }), periodEnd: timestamp('period_end', { withTimezone: true }), observedAt: timestamp('observed_at', { withTimezone: true }).notNull(), staleAfter: timestamp('stale_after', { withTimezone: true }).notNull(), metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [index('workspace_usage_observations_latest_idx').on(table.workspaceId, table.entitlementCode, table.observedAt), check('workspace_usage_observations_value_check', sql`${table.value} >= 0`), check('workspace_usage_observations_period_check', sql`${table.periodEnd} IS NULL OR ${table.periodStart} IS NOT NULL AND ${table.periodEnd} > ${table.periodStart}`), check('workspace_usage_observations_freshness_check', sql`${table.staleAfter} >= ${table.observedAt}`)]);

/** Audited workspace-specific entitlement replacement controlled by administrators. */
export const workspaceEntitlementOverrides = pgTable('workspace_entitlement_overrides', {
	id: uuid('id').primaryKey().defaultRandom(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'restrict' }), entitlementCode: varchar('entitlement_code', { length: 120 }).notNull(), enforcementMode: varchar('enforcement_mode', { length: 30 }), numericValue: bigint('numeric_value', { mode: 'number' }), booleanValue: boolean('boolean_value'), isUnlimited: boolean('is_unlimited').notNull().default(false), reason: text('reason').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }), createdByUserId: uuid('created_by_user_id').notNull().references(() => users.id, { onDelete: 'restrict' }), revokedAt: timestamp('revoked_at', { withTimezone: true }), revokedByUserId: uuid('revoked_by_user_id').references(() => users.id, { onDelete: 'restrict' }), revokeReason: text('revoke_reason'), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(), deletedAt: timestamp('deleted_at', { withTimezone: true }), deleteReason: varchar('delete_reason', { length: 500 }),
}, (table) => [uniqueIndex('workspace_entitlement_overrides_active_unique').on(table.workspaceId, table.entitlementCode).where(sql`${table.revokedAt} IS NULL AND ${table.deletedAt} IS NULL`), index('workspace_entitlement_overrides_expiry_idx').on(table.expiresAt), check('workspace_entitlement_overrides_value_check', sql`(${table.isUnlimited} = true AND ${table.numericValue} IS NULL AND ${table.booleanValue} IS NULL) OR (${table.isUnlimited} = false AND num_nonnulls(${table.numericValue}, ${table.booleanValue}) = 1)`), check('workspace_entitlement_overrides_mode_check', sql`${table.enforcementMode} IS NULL OR ${table.enforcementMode} IN ('hard','soft','metered','informational')`)]);

export const workspaceUsageReservationRelations = relations(workspaceUsageReservations, ({ one }) => ({ workspace: one(workspaces, { fields: [workspaceUsageReservations.workspaceId], references: [workspaces.id] }), subscription: one(workspaceSubscriptions, { fields: [workspaceUsageReservations.subscriptionId], references: [workspaceSubscriptions.id] }) }));
export const workspaceUsageObservationRelations = relations(workspaceUsageObservations, ({ one }) => ({ workspace: one(workspaces, { fields: [workspaceUsageObservations.workspaceId], references: [workspaces.id] }) }));
export const workspaceEntitlementOverrideRelations = relations(workspaceEntitlementOverrides, ({ one }) => ({ workspace: one(workspaces, { fields: [workspaceEntitlementOverrides.workspaceId], references: [workspaces.id] }), createdBy: one(users, { fields: [workspaceEntitlementOverrides.createdByUserId], references: [users.id], relationName: 'usageOverrideCreator' }), revokedBy: one(users, { fields: [workspaceEntitlementOverrides.revokedByUserId], references: [users.id], relationName: 'usageOverrideRevoker' }) }));
