import { Database, ExternalLink, FileCode2, GitBranch, Globe2, LoaderCircle, Pencil, Plus, ScrollText } from 'lucide-react';
import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useOutletContext, useParams } from 'react-router';
import { toast } from 'sonner';

import { Offcanvas } from '@components/ui/offcanvas';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface ApplicationDomain { hostname: string; id: string; isEnabled: boolean; isPrimary: boolean; status: string; tlsStatus: string; type: 'custom' | 'platform' }
interface ApplicationDatabase { databaseId: string; databaseName: string; environmentPrefix: string }
interface Application { applicationPort: number; baseDirectory: string; buildCommand?: string | null; buildPack: string; createdAt: string; databases: ApplicationDatabase[]; domains: ApplicationDomain[]; failureReason?: string | null; id: string; installCommand?: string | null; latestDeployment?: { completedAt?: string | null; createdAt: string; status: string }; name: string; publicUrl?: string | null; publishDirectory?: string | null; resourceStatus?: string | null; runtimeCode: string; runtimeLanguage: string; runtimeVersion: string; sourceRef: string; sourceRepository: string; startCommand?: string | null; status: string }
interface Options { applicationBaseDomain?: string; applicationDomainReady?: boolean; databases: Array<{ databaseName: string; id: string }>; runtimes: Array<{ code: string; defaultPort: number; isDefault: boolean; language: string; version: string }> }
interface ApiBody<T> { data?: T; message: string; status: boolean }

/** Send an authenticated application request and unwrap its response. */
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as ApiBody<T>; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }
const inputClass = 'rounded-xl border border-brand-primary/15 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100';

export default function CustomerApplicationsPage() {
	const { active } = useOutletContext<{ active?: { publicId: number } }>();
	const { applicationId } = useParams();
	const location = useLocation();
	const navigate = useNavigate();
	const creating = location.pathname.endsWith('/create');
	const editing = Boolean(applicationId && new URLSearchParams(location.search).get('mode') === 'edit');
	const [rows, setRows] = useState<Application[]>([]);
	const [options, setOptions] = useState<Options>({ databases: [], runtimes: [] });
	const [loading, setLoading] = useState(true);
	const [submitting, setSubmitting] = useState(false);
	const [logs, setLogs] = useState('');
	const record = rows.find(({ id }) => id === applicationId);
	const load = useCallback(async () => { if (!active) return; setLoading(true); try { const [applications, values] = await Promise.all([api<Application[]>(`/api/v1/workspaces/${active.publicId}/applications`), api<Options>(`/api/v1/workspaces/${active.publicId}/applications/options`)]); setRows(applications); setOptions(values); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load applications.'); } finally { setLoading(false); } }, [active]);
	useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, [load]);

	/** Create or update an application from the active offcanvas form. */
	async function submit(event: FormEvent<HTMLFormElement>): Promise<void> {
		event.preventDefault(); if (!active) return; setSubmitting(true);
		const form = new FormData(event.currentTarget); const runtime = options.runtimes.find(({ code }) => code === form.get('runtimeCode')); const databaseId = String(form.get('databaseId') ?? '');
		const common = { branch: form.get('branch'), installCommand: form.get('installCommand') || undefined, buildCommand: form.get('buildCommand') || undefined, startCommand: form.get('startCommand') || undefined, baseDirectory: form.get('baseDirectory'), publishDirectory: form.get('publishDirectory') || undefined, port: Number(form.get('port') || runtime?.defaultPort) };
		try {
			if (editing && applicationId) await api(`/api/v1/workspaces/${active.publicId}/applications/${applicationId}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(common) });
			else { const result = await api<{ id: string }>(`/api/v1/workspaces/${active.publicId}/applications`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...common, databases: databaseId ? [{ databaseId, environmentPrefix: 'DATABASE' }] : [], name: form.get('name'), subdomain: form.get('subdomain') || undefined, runtimeCode: form.get('runtimeCode'), repository: form.get('repository'), buildPack: form.get('buildPack') }) }); navigate(`/dashboard/applications/${result.id}`, { replace: true }); }
			toast.success(editing ? 'Application updated and deployment queued.' : 'Application deployment queued.'); await load();
			if (editing) navigate(`/dashboard/applications/${applicationId}`, { replace: true });
		} catch (error) { toast.error(error instanceof Error ? error.message : 'Application operation failed.'); } finally { setSubmitting(false); }
	}

	/** Load recent provider logs into the detail drawer. */
	async function loadLogs(): Promise<void> { if (!active || !applicationId) return; try { setLogs((await api<{ logs: string }>(`/api/v1/workspaces/${active.publicId}/applications/${applicationId}/logs`)).logs); } catch (error) { toast.error(error instanceof Error ? error.message : 'Logs unavailable.'); } }
	const form = (isEdit: boolean) => <form className="mt-6 grid gap-5" key={`${record?.id ?? 'new'}-${isEdit}`} onSubmit={(event) => void submit(event)}>
		{!isEdit && <><label className="grid gap-2 font-semibold">Name<input className={inputClass} name="name" required /></label><label className="grid gap-2 font-semibold">Platform subdomain<input className={inputClass} name="subdomain" placeholder="my-app" /></label><label className="grid gap-2 font-semibold">Public Git repository<input className={inputClass} name="repository" placeholder="https://github.com/organisation/repository" required type="url" /></label></>}
		<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-semibold">Branch<input className={inputClass} defaultValue={record?.sourceRef ?? 'main'} name="branch" required /></label>{!isEdit && <label className="grid gap-2 font-semibold">Runtime<select className={inputClass} name="runtimeCode" required>{options.runtimes.map((runtime) => <option key={runtime.code} value={runtime.code}>{runtime.language} {runtime.version}</option>)}</select></label>}{!isEdit && <label className="grid gap-2 font-semibold">Build pack<select className={inputClass} name="buildPack"><option value="nixpacks">Nixpacks</option><option value="static">Static</option><option value="dockerfile">Dockerfile</option></select></label>}<label className="grid gap-2 font-semibold">Port<input className={inputClass} defaultValue={record?.applicationPort ?? options.runtimes.find(({ isDefault }) => isDefault)?.defaultPort ?? 3000} max="65535" min="1" name="port" type="number" /></label></div>
		<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-semibold">Base directory<input className={inputClass} defaultValue={record?.baseDirectory ?? '/'} name="baseDirectory" /></label><label className="grid gap-2 font-semibold">Publish directory<input className={inputClass} defaultValue={record?.publishDirectory ?? ''} name="publishDirectory" /></label></div>
		<details className="rounded-2xl border border-brand-primary/10 p-4" open={isEdit}><summary className="cursor-pointer font-bold">Build commands</summary><div className="mt-4 grid gap-4"><input className={inputClass} defaultValue={record?.installCommand ?? ''} name="installCommand" placeholder="Install command" /><input className={inputClass} defaultValue={record?.buildCommand ?? ''} name="buildCommand" placeholder="Build command" /><input className={inputClass} defaultValue={record?.startCommand ?? ''} name="startCommand" placeholder="Start command" /></div></details>
		{isEdit ? <div className="rounded-2xl border border-brand-primary/10 p-4"><p className="text-sm font-bold">Connected databases</p><p className="mt-1 text-sm text-app-muted">{record?.databases.length ? record.databases.map(({ databaseName }) => databaseName).join(', ') : 'None'} · Existing bindings remain unchanged during configuration edits.</p></div> : <label className="grid gap-2 font-semibold">Connected database<select className={inputClass} name="databaseId"><option value="">No database</option>{options.databases.map((database) => <option key={database.id} value={database.id}>{database.databaseName}</option>)}</select></label>}
		<button className="rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" disabled={submitting} type="submit">{isEdit ? 'Save and deploy' : 'Queue deployment'}</button>
	</form>;

	return <div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Workspace compute</p><h2 className="mt-2 text-4xl font-black">Applications</h2></div><Link className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" to="/dashboard/applications/create"><Plus className="size-4" />Deploy application</Link></div>
		{loading ? <LoaderCircle className="mt-8 size-6 animate-spin" /> : <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((row) => { const primary = row.domains.find((domain) => domain.isPrimary) ?? row.domains[0]; return <Link className="rounded-3xl border border-brand-primary/10 bg-app-surface p-6 transition hover:border-brand-action/60" key={row.id} to={`/dashboard/applications/${row.id}`}><div className="flex items-start justify-between"><FileCode2 className="size-6 text-brand-primary dark:text-brand-action" /><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${row.resourceStatus === 'running' ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : 'bg-amber-500/10 text-amber-700 dark:text-amber-300'}`}>{row.resourceStatus ?? row.status}</span></div><h3 className="mt-5 truncate text-xl font-bold">{row.name}</h3><p className="mt-2 text-sm text-app-muted">{row.runtimeLanguage} {row.runtimeVersion} · {row.buildPack}</p><div className="mt-5 grid gap-2 text-sm"><span className="flex items-center gap-2"><GitBranch className="size-4 text-app-muted" />{row.sourceRef}</span><span className="flex items-center gap-2 truncate"><Database className="size-4 text-app-muted" />{row.databases.length ? row.databases.map(({ databaseName }) => databaseName).join(', ') : 'No database'}</span><span className="flex items-center gap-2 truncate"><Globe2 className="size-4 text-app-muted" />{primary?.hostname ?? 'Domain pending'}</span></div></Link>; })}{!rows.length && <p className="rounded-2xl border border-dashed border-brand-primary/20 p-8 text-center text-app-muted md:col-span-2 xl:col-span-3">No source applications yet.</p>}</div>}
		{creating && <Offcanvas onClose={() => navigate('/dashboard/applications')} title="Deploy application" width="lg">{form(false)}</Offcanvas>}
		{applicationId && <Offcanvas onClose={() => navigate('/dashboard/applications')} title={editing ? `Edit ${record?.name ?? 'application'}` : record?.name ?? 'Application details'} width="xl">{editing ? form(true) : <div className="mt-6 grid gap-6">{record ? <><div className="flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-4 py-2.5 font-bold text-brand-ink" onClick={() => navigate(`/dashboard/applications/${record.id}?mode=edit`)} type="button"><Pencil className="size-4" />Edit</button><Link className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-4 py-2.5 font-bold" to={`/dashboard/applications/${record.id}/domains`}><Globe2 className="size-4" />Domains</Link>{record.publicUrl && <a className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-4 py-2.5 font-bold" href={record.publicUrl} rel="noreferrer" target="_blank">Open <ExternalLink className="size-4" /></a>}<button className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-4 py-2.5 font-bold" onClick={() => void loadLogs()} type="button"><ScrollText className="size-4" />Logs</button></div><dl className="grid gap-4 rounded-2xl border border-brand-primary/10 p-5 sm:grid-cols-2">{[['Stack', `${record.runtimeLanguage} ${record.runtimeVersion} · ${record.buildPack}`], ['Status', record.resourceStatus ?? record.status], ['Repository', record.sourceRepository], ['Branch', record.sourceRef], ['Port', record.applicationPort], ['Base directory', record.baseDirectory], ['Databases', record.databases.length ? record.databases.map(({ databaseName }) => databaseName).join(', ') : 'None'], ['Primary domain', record.domains.find(({ isPrimary }) => isPrimary)?.hostname ?? 'Pending'], ['Latest deployment', record.latestDeployment ? `${record.latestDeployment.status} · ${new Date(record.latestDeployment.createdAt).toLocaleString('en-IN')}` : 'None']].map(([label, value]) => <div key={String(label)}><dt className="text-xs font-bold uppercase text-app-muted">{label}</dt><dd className="mt-1 break-all">{String(value)}</dd></div>)}</dl>{record.failureReason && <p className="rounded-xl bg-red-500/10 p-4 text-red-600 dark:text-red-300">{record.failureReason}</p>}{logs && <pre className="max-h-96 overflow-auto rounded-2xl bg-gray-950 p-5 text-xs text-gray-100">{logs}</pre>}</> : <LoaderCircle className="size-6 animate-spin" />}</div>}</Offcanvas>}
	</div>;
}
