import { ExternalLink, FileCode2, LoaderCircle, Plus, ScrollText } from 'lucide-react';
import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useOutletContext, useParams } from 'react-router';
import { toast } from 'sonner';

import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface ApplicationDomain { hostname: string; id: string; isEnabled: boolean; isPrimary: boolean; status: string; type: 'custom' | 'platform'; verificationToken?: string | null }
interface Application { applicationPort: number; createdAt: string; domains?: ApplicationDomain[]; failureReason?: string | null; id: string; publicUrl?: string | null; requestedDomain?: string | null; resourceStatus?: string | null; runtimeCode: string; runtimeLanguage: string; runtimeVersion: string; sourceRef: string; sourceRepository: string; status: string }
interface Options { applicationBaseDomain?: string; applicationDomainReady?: boolean; databases: Array<{ databaseName: string; id: string }>; runtimes: Array<{ code: string; defaultPort: number; isDefault: boolean; language: string; version: string }> }
interface ApiBody<T> { data?: T; message: string; status: boolean }
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as ApiBody<T>; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }

/** Customer application source, runtime, database binding, and deployment views. */
export default function CustomerApplicationsPage() {
	const { active } = useOutletContext<{ active?: { publicId: number } }>(); const { applicationId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const creating = location.pathname.endsWith('/create'); const [rows, setRows] = useState<Application[]>([]); const [options, setOptions] = useState<Options>({ databases: [], runtimes: [] }); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [logs, setLogs] = useState('');
	const load = useCallback(async () => { if (!active) return; setLoading(true); try { const [applications, values] = await Promise.all([api<Application[]>(`/api/v1/workspaces/${active.publicId}/applications`), api<Options>(`/api/v1/workspaces/${active.publicId}/applications/options`)]); setRows(applications); setOptions(values); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load applications.'); } finally { setLoading(false); } }, [active]);
	useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, [load]);
	async function create(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!active) return; setSubmitting(true); const form = new FormData(event.currentTarget); const runtime = options.runtimes.find(({ code }) => code === form.get('runtimeCode')); const databaseId = String(form.get('databaseId') ?? ''); try { const result = await api<{ id: string }>(`/api/v1/workspaces/${active.publicId}/applications`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), subdomain: form.get('subdomain') || undefined, runtimeCode: form.get('runtimeCode'), repository: form.get('repository'), branch: form.get('branch'), buildPack: form.get('buildPack'), installCommand: form.get('installCommand') || undefined, buildCommand: form.get('buildCommand') || undefined, startCommand: form.get('startCommand') || undefined, baseDirectory: form.get('baseDirectory'), publishDirectory: form.get('publishDirectory') || undefined, port: Number(form.get('port') || runtime?.defaultPort), domain: form.get('domain') || undefined, databases: databaseId ? [{ databaseId, environmentPrefix: 'DATABASE' }] : [] }) }); toast.success('Application deployment queued.'); navigate(`/dashboard/applications/${result.id}`, { replace: true }); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Application creation failed.'); } finally { setSubmitting(false); } }
	async function loadLogs(): Promise<void> { if (!active || !applicationId) return; try { setLogs((await api<{ logs: string }>(`/api/v1/workspaces/${active.publicId}/applications/${applicationId}/logs`)).logs); } catch (error) { toast.error(error instanceof Error ? error.message : 'Logs unavailable.'); } }
	const inputClass = 'rounded-xl border border-brand-primary/15 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100';
	if (creating) return <div className="mx-auto max-w-3xl"><Link className="font-semibold text-brand-primary dark:text-brand-action" to="/dashboard/applications">← Applications</Link><h2 className="mt-5 text-4xl font-black">Deploy application</h2><form className="mt-7 grid gap-5 rounded-3xl border border-brand-primary/10 bg-app-surface p-6" onSubmit={(event) => void create(event)}><label className="grid gap-2 font-semibold">Name<input className={inputClass} name="name" required /></label><label className="grid gap-2 font-semibold">Public Git repository<input className={inputClass} name="repository" placeholder="https://github.com/organisation/repository" required type="url" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-semibold">Branch<input className={inputClass} defaultValue="main" name="branch" required /></label><label className="grid gap-2 font-semibold">Runtime<select className={inputClass} name="runtimeCode" required>{options.runtimes.map((runtime) => <option key={runtime.code} value={runtime.code}>{runtime.language} {runtime.version}</option>)}</select></label><label className="grid gap-2 font-semibold">Build pack<select className={inputClass} name="buildPack"><option value="nixpacks">Nixpacks</option><option value="static">Static</option><option value="dockerfile">Dockerfile</option></select></label><label className="grid gap-2 font-semibold">Port<input className={inputClass} defaultValue={options.runtimes.find(({ isDefault }) => isDefault)?.defaultPort ?? 3000} max="65535" min="1" name="port" type="number" /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-semibold">Base directory<input className={inputClass} defaultValue="/" name="baseDirectory" /></label><label className="grid gap-2 font-semibold">Publish directory<input className={inputClass} name="publishDirectory" /></label></div><details className="rounded-2xl border border-brand-primary/10 p-4"><summary className="cursor-pointer font-bold">Custom commands</summary><div className="mt-4 grid gap-4"><input className={inputClass} name="installCommand" placeholder="Install command" /><input className={inputClass} name="buildCommand" placeholder="Build command" /><input className={inputClass} name="startCommand" placeholder="Start command" /></div></details><label className="grid gap-2 font-semibold">Database<select className={inputClass} name="databaseId"><option value="">No database</option>{options.databases.map((database) => <option key={database.id} value={database.id}>{database.databaseName}</option>)}</select></label><label className="grid gap-2 font-semibold">Custom domain (optional)<input className={inputClass} name="domain" placeholder="app.example.com" /></label><button className="rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" disabled={submitting} type="submit">Queue deployment</button></form></div>;
	if (applicationId) { const record = rows.find(({ id }) => id === applicationId); return <div className="mx-auto max-w-4xl"><Link className="font-semibold text-brand-primary dark:text-brand-action" to="/dashboard/applications">← Applications</Link><h2 className="mt-5 text-4xl font-black">{record?.sourceRepository.split('/').pop() ?? 'Application'}</h2><p className="mt-2 text-app-muted">{record?.runtimeLanguage} {record?.runtimeVersion} · {record?.status}</p><dl className="mt-7 grid gap-4 rounded-3xl border border-brand-primary/10 bg-app-surface p-6 sm:grid-cols-2"><div><dt className="text-xs uppercase text-app-muted">Repository</dt><dd className="mt-1 break-all">{record?.sourceRepository}</dd></div><div><dt className="text-xs uppercase text-app-muted">Branch</dt><dd className="mt-1">{record?.sourceRef}</dd></div><div><dt className="text-xs uppercase text-app-muted">Port</dt><dd className="mt-1">{record?.applicationPort}</dd></div><div><dt className="text-xs uppercase text-app-muted">Domain</dt><dd className="mt-1">{record?.requestedDomain ?? 'Automatic'}</dd></div></dl>{record?.failureReason && <p className="mt-5 rounded-xl bg-red-500/10 p-4 text-red-600 dark:text-red-400">{record.failureReason}</p>}<div className="mt-5 flex flex-wrap gap-3">{record?.publicUrl && <a className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-4 py-3 font-bold text-brand-ink" href={record.publicUrl} rel="noreferrer" target="_blank">Open <ExternalLink className="size-4" /></a>}<button className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-4 py-3 font-bold" onClick={() => void loadLogs()} type="button"><ScrollText className="size-4" />Load logs</button></div>{logs && <pre className="mt-5 max-h-96 overflow-auto rounded-2xl bg-gray-950 p-5 text-xs text-gray-100">{logs}</pre>}</div>; }
	return <div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Workspace compute</p><h2 className="mt-2 text-4xl font-black">Applications</h2></div><Link className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" to="/dashboard/applications/create"><Plus className="size-4" />Deploy application</Link></div>{loading ? <LoaderCircle className="mt-8 size-6 animate-spin" /> : <div className="mt-7 grid gap-4 md:grid-cols-2">{rows.map((row) => <Link className="rounded-3xl border border-brand-primary/10 bg-app-surface p-6" key={row.id} to={`/dashboard/applications/${row.id}`}><FileCode2 className="size-6 text-brand-primary dark:text-brand-action" /><h3 className="mt-5 truncate text-xl font-bold">{row.sourceRepository.split('/').pop()}</h3><p className="mt-2 text-sm capitalize text-app-muted">{row.runtimeLanguage} {row.runtimeVersion} · {row.status}</p></Link>)}{!rows.length && <p className="rounded-2xl border border-dashed border-brand-primary/20 p-8 text-center text-app-muted md:col-span-2">No source applications yet.</p>}</div>}</div>;
}
