import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowLeft, CreditCard, LoaderCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router';

import { SearchableSelect } from '@root/app/components/forms/searchable-select';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';
import { initiatePaymentSchema, type InitiatePaymentInput } from '@schemas/checkout';

interface Checkout { currency: string; packageName: string; status: string; totalMinor: number }
interface Session { action?: string; fields?: Record<string, string>; providerOrderId: string; publicKey?: string; type: 'redirect_form' | 'browser_sdk' | 'mock' }
declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open(): void } } }

const providerLabel = { mock: 'Mock payment', payu: 'PayU', razorpay: 'Razorpay' } as const;

/** Provider-neutral payment screen that hands authoritative sessions to PayU/Razorpay. */
export default function CheckoutPaymentPage() {
	const { checkoutId } = useParams(); const navigate = useNavigate();
	const [checkout, setCheckout] = useState<Checkout>(); const [providers, setProviders] = useState<Array<keyof typeof providerLabel>>([]); const [error, setError] = useState('');
	const { control, formState: { errors, isSubmitting }, handleSubmit, register, setValue } = useForm<InitiatePaymentInput>({ resolver: zodResolver(initiatePaymentSchema), defaultValues: { customerEmail: '', customerName: '', provider: 'payu' } });
	const selectedProvider = useWatch({ control, name: 'provider' });
	useEffect(() => { void Promise.all([authenticatedFetch(`/api/v1/checkouts/${checkoutId}`).then((response) => response.json()), fetch('/api/v1/payments/providers').then((response) => response.json())]).then(([checkoutBody, providerBody]: Array<{ data?: unknown; message: string; status: boolean }>) => { if (!checkoutBody.status || !checkoutBody.data) throw new Error(checkoutBody.message); const available = providerBody.data as Array<keyof typeof providerLabel>; setCheckout(checkoutBody.data as Checkout); setProviders(available); if (available[0]) setValue('provider', available.includes('payu') ? 'payu' : available[0]); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to prepare payment.')); }, [checkoutId, setValue]);

	function submitRedirect(session: Session): void { const form = document.createElement('form'); form.method = 'POST'; form.action = session.action ?? ''; for (const [name, value] of Object.entries(session.fields ?? {})) { const input = document.createElement('input'); input.type = 'hidden'; input.name = name; input.value = value; form.append(input); } document.body.append(form); form.submit(); }
	async function loadRazorpay(): Promise<void> { if (window.Razorpay) return; await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('Unable to load Razorpay Checkout.')); document.head.append(script); }); }
	const submit = handleSubmit(async (input) => { setError(''); const response = await authenticatedFetch(`/api/v1/checkouts/${checkoutId}/payment`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const body = await response.json() as { data?: { session: Session }; message: string; status: boolean }; if (!response.ok || !body.status || !body.data) { setError(body.message); return; } const session = body.data.session; if (session.type === 'redirect_form') { submitRedirect(session); return; } if (session.type === 'mock') { const result = await authenticatedFetch('/api/v1/payments/mock/callback', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ result: 'success', order_id: session.providerOrderId, amount_minor: String(checkout?.totalMinor ?? 0), currency: checkout?.currency ?? 'INR' }) }); const resultBody = await result.json() as { data?: { nextUrl?: string }; message: string; status: boolean }; if (!result.ok || !resultBody.data?.nextUrl) { setError(resultBody.message); return; } navigate(resultBody.data.nextUrl); return; } await loadRazorpay(); const Razorpay = window.Razorpay; if (!Razorpay) throw new Error('Razorpay Checkout is unavailable.'); new Razorpay({ key: session.publicKey, order_id: session.providerOrderId, amount: checkout?.totalMinor, currency: checkout?.currency, name: 'Qubit Hosting', description: checkout?.packageName, prefill: { name: input.customerName, email: input.customerEmail }, handler: async (payment: Record<string, string>) => { const verified = await authenticatedFetch('/api/v1/payments/razorpay/callback', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payment) }); const verifiedBody = await verified.json() as { data?: { nextUrl?: string }; message: string }; if (!verified.ok || !verifiedBody.data?.nextUrl) { setError(verifiedBody.message); return; } navigate(verifiedBody.data.nextUrl); } }).open(); });
	if (!checkout && !error) return <main className="grid min-h-screen place-items-center bg-app-canvas"><LoaderCircle className="size-7 animate-spin text-brand-primary" /></main>;
	return <main className="min-h-screen bg-app-canvas px-5 py-10 text-app-text"><form className="mx-auto max-w-2xl rounded-[2rem] border border-brand-primary/10 bg-app-surface p-6 sm:p-10" onSubmit={submit}><Link className="inline-flex items-center gap-2 text-sm text-app-muted" to="/"><ArrowLeft className="size-4" /> Home</Link><CreditCard className="mt-10 size-8 text-brand-primary dark:text-brand-action" /><h1 className="mt-4 text-4xl font-black">Complete payment</h1><p className="mt-3 text-app-muted">{checkout?.packageName} · ₹{((checkout?.totalMinor ?? 0) / 100).toLocaleString('en-IN')}</p>{error && <p className="mt-5 rounded-xl bg-rose-500/10 p-3 text-sm text-rose-600">{error}</p>}<div className="mt-7 grid gap-4"><label className="font-semibold">Full name<input className="mt-2 w-full rounded-xl border border-brand-primary/15 bg-app-canvas px-4 py-3" {...register('customerName')} />{errors.customerName && <span className="text-xs text-rose-500">{errors.customerName.message}</span>}</label><label className="font-semibold">Billing email<input className="mt-2 w-full rounded-xl border border-brand-primary/15 bg-app-canvas px-4 py-3" type="email" {...register('customerEmail')} />{errors.customerEmail && <span className="text-xs text-rose-500">{errors.customerEmail.message}</span>}</label><div><span className="font-semibold">Payment provider</span><SearchableSelect className="mt-2" onChange={(value) => setValue('provider', value as InitiatePaymentInput['provider'], { shouldValidate: true })} options={providers.map((provider) => ({ label: providerLabel[provider], value: provider }))} searchable={false} value={selectedProvider} /></div></div><button className="mt-8 inline-flex w-full items-center justify-center rounded-2xl bg-brand-action px-5 py-4 font-bold text-brand-ink disabled:opacity-60" disabled={isSubmitting || providers.length === 0} type="submit">{isSubmitting ? <LoaderCircle className="size-5 animate-spin" /> : 'Continue securely'}</button></form></main>;
}
