import { Eye, KeyRound, LoaderCircle, Plus, RotateCw, Trash2 } from 'lucide-react';
import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useOutletContext, useParams } from 'react-router';
import { toast } from 'sonner';

import { DatabaseBackups } from '@components/customer/DatabaseBackups';
import { DataTable, StickyActionsCell, StickyActionsHeader } from '@components/ui/data-table';
import { Offcanvas } from '@components/ui/offcanvas';
import { DestructiveConfirmation, type DestructiveConfirmationValue } from '@components/ui/destructive-confirmation';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface DatabaseRecord { connectedApplications: Array<{ id: string; name: string }>; connectionLimit?: number | null; createdAt: string; databaseName: string; displayName: string; engine: 'mysql' | 'postgresql'; engineVersion: string; id: string; status: string; storageQuotaMb?: number | null; username: string }
interface Credential { databaseName: string; engine: string; host: string; password: string; port: number; username: string }
interface ApiBody<T> { data?: T; message: string; status: boolean }
const inputClass = 'rounded-xl border border-brand-primary/15 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100';
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as ApiBody<T>; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }

export default function CustomerDatabasesPage() {
	const { active } = useOutletContext<{ active?: { publicId: number } }>(); const { databaseId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const creating = location.pathname.endsWith('/create'); const deleting = new URLSearchParams(location.search).get('action') === 'delete';
	const [rows, setRows] = useState<DatabaseRecord[]>([]); const [credentialRecord, setCredentialRecord] = useState<{ databaseId: string; value: Credential }>(); const [passwordVisible, setPasswordVisible] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
	const record = rows.find(({ id }) => id === databaseId);
	const credential = credentialRecord && credentialRecord.databaseId === databaseId ? credentialRecord.value : undefined;
	const load = useCallback(async () => { if (!active) return; setLoading(true); try { setRows(await api<DatabaseRecord[]>(`/api/v1/workspaces/${active.publicId}/databases`)); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load databases.'); } finally { setLoading(false); } }, [active]);
	useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, [load]);
	async function create(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!active) return; setSubmitting(true); const form = new FormData(event.currentTarget); try { const result = await api<{ credential: Credential; database: DatabaseRecord }>(`/api/v1/workspaces/${active.publicId}/databases`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), engine: form.get('engine'), connectionLimit: Number(form.get('connectionLimit')), storageQuotaMb: Number(form.get('storageQuotaMb')) }) }); setCredentialRecord({ databaseId: result.database.id, value: result.credential }); setPasswordVisible(true); toast.success('Database created. Save the credential now.'); navigate(`/dashboard/databases/${result.database.id}`, { replace: true }); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Database creation failed.'); } finally { setSubmitting(false); } }
	async function credentialAction(action: 'credentials' | 'rotate'): Promise<void> { if (!active || !databaseId) return; setSubmitting(true); try { setCredentialRecord({ databaseId, value: await api<Credential>(`/api/v1/workspaces/${active.publicId}/databases/${databaseId}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }) }); setPasswordVisible(true); toast.success(action === 'rotate' ? 'Credential rotated.' : 'Credential revealed.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Credential action failed.'); } finally { setSubmitting(false); } }
	async function deleteDatabase(value: DestructiveConfirmationValue): Promise<void> { if (!active || !record) return; setSubmitting(true); try { await api<{ id: string }>(`/api/v1/workspaces/${active.publicId}/databases/${record.id}`, { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ acceptedImpact: value.acceptedImpact, confirmationName: value.confirmationName, connectedApplicationNames: value.connectedResourceNames }) }); toast.success('Database permanently deleted.'); setCredentialRecord(undefined); navigate('/dashboard/databases', { replace: true }); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Database deletion failed.'); } finally { setSubmitting(false); } }
	return <div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Workspace data</p><h2 className="mt-2 text-4xl font-black">Databases</h2></div><Link className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" to="/dashboard/databases/create"><Plus className="size-4" />Create Database</Link></div>
		{loading ? <LoaderCircle className="mt-8 size-6 animate-spin" /> : <div className="mt-7"><DataTable minimumWidth="70rem"><thead className="bg-app-canvas text-left text-xs font-bold uppercase text-app-muted"><tr><th className="px-5 py-3">Database</th><th className="px-5 py-3">Engine</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">User</th><th className="px-5 py-3">Password</th><th className="px-5 py-3">Connected apps</th><th className="px-5 py-3">Limits</th><th className="px-5 py-3">Created</th><StickyActionsHeader /></tr></thead><tbody className="divide-y divide-brand-primary/10">{rows.map((row) => <tr key={row.id}><td className="px-5 py-4 font-bold">{row.databaseName}</td><td className="px-5 py-4 capitalize">{row.engine} {row.engineVersion}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold capitalize text-emerald-700 dark:text-emerald-300">{row.status}</span></td><td className="px-5 py-4 font-mono text-xs">{row.username}</td><td className="px-5 py-4 font-mono">••••••••••••</td><td className="px-5 py-4">{row.connectedApplications.length ? row.connectedApplications.map(({ name }) => name).join(', ') : 'None'}</td><td className="px-5 py-4">{row.connectionLimit ?? '—'} connections · {row.storageQuotaMb ?? '—'} MB</td><td className="px-5 py-4">{new Date(row.createdAt).toLocaleDateString('en-IN')}</td><StickyActionsCell><Link aria-label={`View ${row.databaseName}`} className="rounded-lg p-2 hover:bg-brand-primary/5" to={`/dashboard/databases/${row.id}`}><Eye className="size-4" /></Link></StickyActionsCell></tr>)}{!rows.length && <tr><td className="px-5 py-10 text-center text-app-muted" colSpan={9}>No databases yet.</td></tr>}</tbody></DataTable></div>}
		{creating && <Offcanvas onClose={() => navigate('/dashboard/databases')} title="Create Database" width="md"><form className="mt-6 grid gap-5" onSubmit={(event) => void create(event)}><label className="grid gap-2 font-semibold">Display Name<input className={inputClass} name="name" required /></label><label className="grid gap-2 font-semibold">Engine<select className={inputClass} name="engine"><option value="postgresql">PostgreSQL</option><option value="mysql">MySQL</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-semibold">Connection Limit<input className={inputClass} defaultValue="10" min="1" name="connectionLimit" type="number" /></label><label className="grid gap-2 font-semibold">Storage Quota (MB)<input className={inputClass} defaultValue="1024" min="128" name="storageQuotaMb" type="number" /></label></div><button className="rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" disabled={submitting} type="submit">Create Database</button></form></Offcanvas>}
		{databaseId && <Offcanvas onClose={() => navigate('/dashboard/databases')} title={record?.databaseName ?? 'Database details'} width="xl"><div className="mt-6 grid gap-6">{record ? <><dl className="grid gap-4 rounded-2xl border border-brand-primary/10 p-5 sm:grid-cols-2 lg:grid-cols-3">{[['Engine', `${record.engine} ${record.engineVersion}`], ['Status', record.status], ['Username', record.username], ['Password', passwordVisible && credential ? credential.password : '••••••••••••'], ['Connected applications', record.connectedApplications.length ? record.connectedApplications.map(({ name }) => name).join(', ') : 'None'], ['Connection limit', record.connectionLimit ?? '—'], ['Storage quota', `${record.storageQuotaMb ?? '—'} MB`], ['Host', credential?.host ?? 'Reveal credentials to view'], ['Port', credential?.port ?? '—']].map(([label, value]) => <div key={String(label)}><dt className="text-xs font-bold uppercase text-app-muted">{label}</dt><dd className="mt-1 break-all font-mono text-sm">{String(value)}</dd></div>)}</dl><div className="flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-4 py-3 font-bold" disabled={submitting} onClick={() => void credentialAction('credentials')} type="button"><KeyRound className="size-4" />Reveal credentials</button><button className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-4 py-3 font-bold text-brand-ink" disabled={submitting} onClick={() => void credentialAction('rotate')} type="button"><RotateCw className="size-4" />Rotate password</button>{credential && <button className="rounded-xl border border-brand-primary/15 px-4 py-3 font-bold" onClick={() => setPasswordVisible((value) => !value)} type="button">{passwordVisible ? 'Mask password' : 'Show password'}</button>}<button className="ml-auto inline-flex items-center gap-2 rounded-xl border border-red-500/30 px-4 py-3 font-bold text-red-600 dark:text-red-300" disabled={submitting} onClick={() => navigate(`/dashboard/databases/${record.id}?action=delete`)} type="button"><Trash2 className="size-4" />Delete Database</button></div>{active && <DatabaseBackups databaseId={databaseId} databaseName={record.databaseName} workspacePublicId={active.publicId} />}</> : <LoaderCircle className="size-6 animate-spin" />}</div></Offcanvas>}
		{deleting && record && <DestructiveConfirmation busy={submitting} connectedResourceLabel="project" connectedResourceNames={record.connectedApplications.map(({ name }) => name)} description="This permanently removes the database, its user, credentials, backups retained separately, and all project bindings. This cannot be undone." onCancel={() => navigate(`/dashboard/databases/${record.id}`, { replace: true })} onConfirm={deleteDatabase} resourceName={record.databaseName} title="Delete Database" />}
	</div>;
}
