import { Database, LoaderCircle, Plus, RotateCw, KeyRound } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Link, useLocation, useNavigate, useOutletContext, useParams } from 'react-router';
import { toast } from 'sonner';

import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';
import { DatabaseBackups } from '@components/customer/DatabaseBackups';

interface DatabaseRecord { connectionLimit?: number | null; createdAt: string; databaseName: string; engine: 'mysql' | 'postgresql'; engineVersion: string; id: string; status: string; storageQuotaMb?: number | null; username: string }
interface Credential { databaseName: string; engine: string; host: string; password: string; port: number; username: string }
interface ApiBody<T> { data?: T; message: string; status: boolean }

async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as ApiBody<T>; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }

export default function CustomerDatabasesPage() {
	const { active } = useOutletContext<{ active?: { publicId: number } }>(); const { databaseId } = useParams(); const location = useLocation(); const navigate = useNavigate(); const creating = location.pathname.endsWith('/create'); const [rows, setRows] = useState<DatabaseRecord[]>([]); const [credential, setCredential] = useState<Credential>(); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
	const load = useCallback(async () => { if (!active) return; setLoading(true); try { setRows(await api<DatabaseRecord[]>(`/api/v1/workspaces/${active.publicId}/databases`)); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load databases.'); } finally { setLoading(false); } }, [active]);
	useEffect(() => { const timeout = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeout); }, [load]);
	async function create(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!active) return; setSubmitting(true); const form = new FormData(event.currentTarget); try { const result = await api<{ credential: Credential; database: DatabaseRecord }>(`/api/v1/workspaces/${active.publicId}/databases`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), engine: form.get('engine'), connectionLimit: Number(form.get('connectionLimit')), storageQuotaMb: Number(form.get('storageQuotaMb')) }) }); setCredential(result.credential); toast.success('Database created. Save the credential now.'); navigate(`/dashboard/databases/${result.database.id}`, { replace: true }); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Database creation failed.'); } finally { setSubmitting(false); } }
	async function credentialAction(action: 'credentials' | 'rotate'): Promise<void> { if (!active || !databaseId) return; setSubmitting(true); try { setCredential(await api<Credential>(`/api/v1/workspaces/${active.publicId}/databases/${databaseId}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' })); toast.success(action === 'rotate' ? 'Credential rotated.' : 'Credential revealed.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Credential action failed.'); } finally { setSubmitting(false); } }
	if (creating) return <div className="mx-auto max-w-2xl"><Link className="font-semibold text-brand-primary dark:text-brand-action" to="/dashboard/databases">← Databases</Link><h2 className="mt-5 text-4xl font-black">Create database</h2><form className="mt-7 grid gap-5 rounded-3xl border border-brand-primary/10 bg-app-surface p-6" onSubmit={(event) => void create(event)}><label className="grid gap-2 font-semibold">Display name<input className="rounded-xl border border-brand-primary/15 bg-app-canvas px-4 py-3" name="name" required /></label><label className="grid gap-2 font-semibold">Engine<select className="rounded-xl border border-brand-primary/15 bg-app-canvas px-4 py-3" name="engine"><option value="postgresql">PostgreSQL</option><option value="mysql">MySQL</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 font-semibold">Connection limit<input className="rounded-xl border border-brand-primary/15 bg-app-canvas px-4 py-3" defaultValue="10" min="1" name="connectionLimit" type="number" /></label><label className="grid gap-2 font-semibold">Storage quota (MB)<input className="rounded-xl border border-brand-primary/15 bg-app-canvas px-4 py-3" defaultValue="1024" min="128" name="storageQuotaMb" type="number" /></label></div><button className="rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" disabled={submitting} type="submit">Create database</button></form></div>;
	if (databaseId) { const record = rows.find((item) => item.id === databaseId); return <div className="mx-auto max-w-4xl"><Link className="font-semibold text-brand-primary dark:text-brand-action" to="/dashboard/databases">← Databases</Link><h2 className="mt-5 text-4xl font-black">{record?.databaseName ?? 'Database'}</h2><p className="mt-2 text-app-muted">{record?.engine} {record?.engineVersion} · {record?.status}</p><div className="mt-6 flex flex-wrap gap-3"><button className="inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-4 py-3 font-bold" disabled={submitting} onClick={() => void credentialAction('credentials')} type="button"><KeyRound className="size-4" />Reveal credentials</button><button className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-4 py-3 font-bold text-brand-ink" disabled={submitting} onClick={() => void credentialAction('rotate')} type="button"><RotateCw className="size-4" />Rotate password</button></div>{credential && <section className="mt-6 rounded-3xl border border-amber-500/30 bg-amber-500/10 p-6"><h3 className="font-bold">Save this credential securely</h3><p className="mt-1 text-sm text-app-muted">Closing this page hides it again.</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2">{Object.entries(credential).map(([key, value]) => <div key={key}><dt className="text-xs uppercase text-app-muted">{key}</dt><dd className="mt-1 break-all font-mono">{String(value)}</dd></div>)}</dl></section>}{active && record && <DatabaseBackups databaseId={databaseId} databaseName={record.databaseName} workspacePublicId={active.publicId} />}</div>; }
	return <div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Workspace data</p><h2 className="mt-2 text-4xl font-black">Databases</h2></div><Link className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" to="/dashboard/databases/create"><Plus className="size-4" />Create database</Link></div>{loading ? <LoaderCircle className="mt-8 size-6 animate-spin" /> : <div className="mt-7 grid gap-4 md:grid-cols-2">{rows.map((row) => <Link className="rounded-3xl border border-brand-primary/10 bg-app-surface p-6" key={row.id} to={`/dashboard/databases/${row.id}`}><Database className="size-6 text-brand-primary dark:text-brand-action" /><h3 className="mt-5 text-xl font-bold">{row.databaseName}</h3><p className="mt-2 text-sm capitalize text-app-muted">{row.engine} {row.engineVersion} · {row.status}</p></Link>)}{!rows.length && <p className="rounded-2xl border border-dashed border-brand-primary/20 p-8 text-center text-app-muted md:col-span-2">No databases yet.</p>}</div>}</div>;
}
