import { AlertTriangle, CheckCircle2, LoaderCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useOutletContext } from 'react-router';

import type { WorkspaceSummary } from '@root/app/layouts/customer';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface UsageItem { code: string; current: number; limit: number | null; unlimited: boolean; mode: string; pending: number; observation: null | { unit: string | null; source: string; observedAt: string; staleAfter: string; status: string } }

/** Customer-visible usage, policy, reservation, and observation freshness view. */
export default function UsagePage() {
	const { active } = useOutletContext<{ active?: WorkspaceSummary }>(); const [items, setItems] = useState<UsageItem[]>([]); const [generatedAt, setGeneratedAt] = useState(''); const [error, setError] = useState('');
	useEffect(() => { if (!active) return; void authenticatedFetch(`/api/v1/workspaces/${active.publicId}/usage`).then(async (response) => { const body = await response.json() as { data?: { usage: UsageItem[]; generatedAt: string }; message: string; status: boolean }; if (!response.ok || !body.status || !body.data) throw new Error(body.message); setItems(body.data.usage); setGeneratedAt(body.data.generatedAt); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Usage unavailable.')); }, [active]);
	if (!active || (!items.length && !error)) return <div className="grid min-h-56 place-items-center"><LoaderCircle className="size-6 animate-spin" /></div>;
	return <section className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Capacity</p><h1 className="mt-2 text-4xl font-black">Workspace usage</h1><p className="mt-3 text-app-muted">Live counts include pending reservations. Measured values show when their provider observation becomes stale.</p>{error && <p className="mt-6 rounded-xl bg-rose-500/10 p-3 text-rose-600 dark:text-rose-300">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => { const exceeded = item.limit !== null && item.current + item.pending >= item.limit; const percent = item.limit ? Math.min(100, ((item.current + item.pending) / item.limit) * 100) : 0; return <article className="rounded-3xl border border-brand-primary/10 bg-app-surface p-6" key={item.code}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-app-muted">{item.mode}</p><h2 className="mt-2 font-black">{item.code}</h2></div>{exceeded ? <AlertTriangle className="size-5 text-amber-500" /> : <CheckCircle2 className="size-5 text-emerald-500" />}</div><p className="mt-6 text-3xl font-black">{item.current}<span className="text-base font-semibold text-app-muted"> / {item.unlimited ? 'Unlimited' : item.limit}</span></p>{item.pending > 0 && <p className="mt-1 text-xs text-amber-600 dark:text-amber-300">+{item.pending} pending reservation</p>}{item.limit !== null && <div className="mt-4 h-2 overflow-hidden rounded-full bg-brand-primary/10"><div className={`h-full rounded-full ${exceeded ? 'bg-amber-500' : 'bg-brand-action'}`} style={{ width: `${percent}%` }} /></div>}{item.observation && <div className={`mt-5 rounded-xl p-3 text-xs ${item.observation.status === 'stale' ? 'bg-amber-500/10 text-amber-700 dark:text-amber-300' : 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300'}`}><strong className="capitalize">{item.observation.status}</strong> · {item.observation.source}<br />Observed {new Date(item.observation.observedAt).toLocaleString()}</div>}</article>; })}</div>{generatedAt && <p className="mt-5 text-xs text-app-muted">Generated {new Date(generatedAt).toLocaleString()}</p>}</section>;
}
