import { Clock3, History, LoaderCircle, Pencil, Plus, Trash2, X } from 'lucide-react';
import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface CronJob { command: string; frequency: string; id: string; isEnabled: boolean; name: string; timeoutSeconds: number }
interface CronData { jobs: CronJob[]; limits: { allowed: boolean; maximumJobs: number | null; maximumTimeoutSeconds: number; minimumIntervalMinutes: number }; preset: { command: string | null; editable: boolean; preset: string } | null }
interface Execution { createdAt?: string; duration?: number | null; message?: string | null; startedAt?: string | null; status: string; uuid: string }
interface ApiBody<T> { data?: T; message: string; status: boolean }
const inputClass = 'rounded-xl border border-brand-primary/15 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100';
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as ApiBody<T>; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }

/** Plan-aware scheduled-task editor for one deployed application. */
export function ApplicationCronJobs({ applicationId, workspaceId }: { applicationId: string; workspaceId: number }) {
	const base = `/api/v1/workspaces/${workspaceId}/applications/${applicationId}/cron-jobs`;
	const [data, setData] = useState<CronData>(); const [editing, setEditing] = useState<CronJob>(); const [formOpen, setFormOpen] = useState(false); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [history, setHistory] = useState<{ job: CronJob; rows: Execution[] }>();
	const load = useCallback(async () => { setLoading(true); try { setData(await api<CronData>(base)); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load scheduled tasks.'); } finally { setLoading(false); } }, [base]);
	useEffect(() => { void api<CronData>(base).then(setData).catch((error: unknown) => toast.error(error instanceof Error ? error.message : 'Unable to load scheduled tasks.')).finally(() => setLoading(false)); }, [base]);
	async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); const form = new FormData(event.currentTarget); try { await api(editing ? `${base}/${editing.id}` : base, { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: form.get('name'), command: form.get('command') || undefined, frequency: form.get('frequency'), timeoutSeconds: Number(form.get('timeoutSeconds')), isEnabled: form.get('isEnabled') === 'on' }) }); toast.success(editing ? 'Scheduled task updated.' : 'Scheduled task created.'); setEditing(undefined); setFormOpen(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save scheduled task.'); } finally { setSubmitting(false); } }
	async function remove(job: CronJob) { if (!window.confirm(`Delete “${job.name}”?`)) return; try { await api(`${base}/${job.id}`, { method: 'DELETE' }); toast.success('Scheduled task deleted.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to delete scheduled task.'); } }
	async function showHistory(job: CronJob) { try { setHistory({ job, rows: await api<Execution[]>(`${base}/${job.id}/executions`) }); } catch (error) { toast.error(error instanceof Error ? error.message : 'Execution history unavailable.'); } }
	if (loading) return <LoaderCircle className="size-5 animate-spin" />;
	if (!data?.preset) return <p className="rounded-2xl border border-dashed border-brand-primary/20 p-5 text-sm text-app-muted">Scheduled tasks are unavailable for static applications.</p>;
	const defaultHours = Math.max(1, Math.ceil(data.limits.minimumIntervalMinutes / 60));
	return <section className="rounded-2xl border border-brand-primary/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 font-bold"><Clock3 className="size-5" />Scheduled tasks</h3><p className="mt-1 text-sm text-app-muted">Runs inside this application. Minimum interval {data.limits.minimumIntervalMinutes} min · timeout up to {data.limits.maximumTimeoutSeconds}s.</p></div><button className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-4 py-2.5 font-bold text-brand-ink disabled:opacity-50" disabled={!data.limits.allowed || (data.limits.maximumJobs !== null && data.jobs.length >= data.limits.maximumJobs)} onClick={() => { setEditing(undefined); setFormOpen(true); }} type="button"><Plus className="size-4" />Add task</button></div>
		{!data.limits.allowed && <p className="mt-4 rounded-xl bg-amber-500/10 p-3 text-sm text-amber-700 dark:text-amber-300">Not included in this workspace plan.</p>}
		<div className="mt-4 grid gap-3">{data.jobs.map((job) => <article className="rounded-xl bg-app-bg p-4" key={job.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{job.name} <span className="ml-2 text-xs text-app-muted">{job.isEnabled ? 'Enabled' : 'Disabled'}</span></p><code className="mt-2 block break-all text-xs text-app-muted">{job.frequency} · {job.command}</code></div><div className="flex gap-2"><button aria-label="History" className="rounded-lg border border-brand-primary/15 p-2" onClick={() => void showHistory(job)} type="button"><History className="size-4" /></button><button aria-label="Edit" className="rounded-lg border border-brand-primary/15 p-2" onClick={() => { setEditing(job); setFormOpen(true); }} type="button"><Pencil className="size-4" /></button><button aria-label="Delete" className="rounded-lg border border-red-500/20 p-2 text-red-600" onClick={() => void remove(job)} type="button"><Trash2 className="size-4" /></button></div></div></article>)}{!data.jobs.length && <p className="rounded-xl border border-dashed border-brand-primary/20 p-5 text-center text-sm text-app-muted">No scheduled tasks configured.</p>}</div>
		{formOpen && <form className="mt-5 grid gap-4 rounded-2xl border border-brand-action/30 p-5" onSubmit={(event) => void save(event)}><div className="flex justify-between"><h4 className="font-bold">{editing ? 'Edit task' : 'New task'}</h4><button aria-label="Close" onClick={() => setFormOpen(false)} type="button"><X className="size-4" /></button></div><label className="grid gap-2 text-sm font-semibold">Name<input className={inputClass} defaultValue={editing?.name} name="name" required /></label><label className="grid gap-2 text-sm font-semibold">Cron frequency<input className={inputClass} defaultValue={editing?.frequency ?? `0 */${defaultHours} * * *`} name="frequency" required /><span className="text-xs font-normal text-app-muted">Five fields: minute, hour, day, month, weekday.</span></label>{data.preset.editable ? <label className="grid gap-2 text-sm font-semibold">{data.preset.preset === 'django-command' ? 'Django management command' : data.preset.preset === 'rails-command' ? 'Rails command' : 'Command'}<input className={inputClass} defaultValue={editing?.command.replace(/^python manage\.py |^bundle exec rails /, '')} name="command" required /><span className="text-xs font-normal text-app-muted">Runs only inside this project container.</span></label> : <p className="rounded-xl bg-app-bg p-3 text-sm">Framework command: <code>{data.preset.command}</code></p>}<label className="grid gap-2 text-sm font-semibold">Timeout seconds<input className={inputClass} defaultValue={editing?.timeoutSeconds ?? Math.min(300, data.limits.maximumTimeoutSeconds)} max={data.limits.maximumTimeoutSeconds} min="1" name="timeoutSeconds" required type="number" /></label><label className="flex items-center gap-3 text-sm font-semibold"><input defaultChecked={editing?.isEnabled ?? true} name="isEnabled" type="checkbox" />Enabled</label><button className="rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink" disabled={submitting} type="submit">{submitting ? 'Saving…' : 'Save task'}</button></form>}
		{history && <div className="mt-5 rounded-2xl border border-brand-primary/10 p-5"><div className="flex justify-between"><h4 className="font-bold">{history.job.name} history</h4><button aria-label="Close" onClick={() => setHistory(undefined)} type="button"><X className="size-4" /></button></div><div className="mt-3 grid gap-2">{history.rows.map((row) => <div className="rounded-xl bg-app-bg p-3 text-sm" key={row.uuid}><strong className="capitalize">{row.status}</strong> · {row.duration ?? '—'}s · {row.startedAt || row.createdAt ? new Date(row.startedAt ?? row.createdAt!).toLocaleString('en-IN') : '—'}{row.message && <pre className="mt-2 max-h-32 overflow-auto whitespace-pre-wrap text-xs text-app-muted">{row.message}</pre>}</div>)}{!history.rows.length && <p className="text-sm text-app-muted">No provider executions recorded yet.</p>}</div></div>}
	</section>;
}
