import { describe, expect, it } from 'vitest';

import { databaseSchemaMutationSchema } from '@schemas/databaseSchema';
import { databaseColumnSql } from '@services/databases/databaseSchemaService';

describe('database schema mutation validation', () => {
	it('accepts a bounded table definition with a generated primary key', () => {
		const result = databaseSchemaMutationSchema.safeParse({
			operation: 'create_table',
			schema: 'public',
			table: 'projects',
			columns: [{ name: 'id', type: 'bigint', nullable: false, primaryKey: true, autoIncrement: true, default: { kind: 'none' } }],
		});
		expect(result.success).toBe(true);
	});

	it('rejects duplicate columns, invalid decimal shape, and missing destructive acknowledgement', () => {
		expect(databaseSchemaMutationSchema.safeParse({ operation: 'create_table', schema: 'public', table: 'projects', columns: [
			{ name: 'id', type: 'integer' }, { name: 'id', type: 'integer' },
		] }).success).toBe(false);
		expect(databaseSchemaMutationSchema.safeParse({ operation: 'add_column', schema: 'public', table: 'projects', column: { name: 'amount', type: 'decimal', scale: 3 } }).success).toBe(false);
		expect(databaseSchemaMutationSchema.safeParse({ operation: 'drop_table', schema: 'public', table: 'projects', confirmation: 'public.projects', acceptedImpact: false }).success).toBe(false);
	});

	it('requires matching local and referenced foreign-key columns', () => {
		expect(databaseSchemaMutationSchema.safeParse({
			operation: 'add_foreign_key', schema: 'public', table: 'orders', constraintName: 'orders_customer_fk', columns: ['customer_id', 'tenant_id'],
			referenceSchema: 'public', referenceTable: 'customers', referenceColumns: ['id'], onDelete: 'cascade', onUpdate: 'no_action',
		}).success).toBe(false);
	});
});

describe('database schema SQL modelling', () => {
	it('quotes identifiers and maps portable types per engine', () => {
		const column = { name: 'display"name', type: 'string' as const, length: 120, nullable: false, primaryKey: false, autoIncrement: false, default: { kind: 'literal' as const, value: "O'Reilly" } };
		expect(databaseColumnSql('postgresql', column)).toBe('"display""name" VARCHAR(120) NOT NULL DEFAULT \'O\'\'Reilly\'');
		expect(databaseColumnSql('mysql', { ...column, name: 'display`name' })).toBe('`display``name` VARCHAR(120) NOT NULL DEFAULT \'O\'\'Reilly\'');
	});

	it('uses engine-native identity and JSON types', () => {
		expect(databaseColumnSql('postgresql', { name: 'id', type: 'bigint', nullable: false, primaryKey: true, autoIncrement: true, default: { kind: 'none' } })).toContain('BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
		expect(databaseColumnSql('mysql', { name: 'payload', type: 'json', nullable: true, primaryKey: false, autoIncrement: false, default: { kind: 'none' } })).toBe('`payload` JSON NULL');
	});
});
