import { useEffect, useState } from 'react';
import { Link } from 'react-router';

import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface CheckoutAttempt { amountMinor: number; checkoutId: number; checkoutStatus: string; createdAt: string; currency: string; id: string; packageName: string; provider: string; status: string }
const money = (minor: number, currency: string) => new Intl.NumberFormat('en-IN', { currency, maximumFractionDigits: 2, style: 'currency' }).format(minor / 100);

/** Displays every hosted payment session, regardless of its outcome. */
export function CheckoutAttemptHistory() {
	const [attempts, setAttempts] = useState<CheckoutAttempt[]>([]);
	useEffect(() => { void authenticatedFetch('/api/v1/checkouts').then((response) => response.json()).then((body: { data?: CheckoutAttempt[]; status: boolean }) => setAttempts(body.status ? body.data ?? [] : [])); }, []);
	return <article className="overflow-hidden rounded-3xl border border-brand-primary/10 bg-app-surface"><div className="border-b border-brand-primary/10 p-6"><h3 className="text-xl font-black">Checkout history</h3><p className="mt-1 text-sm text-app-muted">Every payment-gateway visit remains visible, even when payment was not completed.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[48rem] text-left text-sm"><thead className="bg-brand-primary/5 text-xs uppercase tracking-wider text-app-muted"><tr><th className="px-6 py-3">Date</th><th className="px-6 py-3">Plan</th><th className="px-6 py-3">Provider</th><th className="px-6 py-3">Amount</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Action</th></tr></thead><tbody className="divide-y divide-brand-primary/10">{attempts.map((attempt) => <tr key={attempt.id}><td className="px-6 py-4">{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(attempt.createdAt))}</td><td className="px-6 py-4 font-semibold">{attempt.packageName}<span className="block text-xs font-normal text-app-muted">#{attempt.checkoutId}</span></td><td className="px-6 py-4 capitalize">{attempt.provider}</td><td className="px-6 py-4 font-semibold">{money(attempt.amountMinor, attempt.currency)}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold capitalize ${attempt.status === 'verified' ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : ['failed', 'cancelled'].includes(attempt.status) ? 'bg-rose-500/10 text-rose-700 dark:text-rose-300' : 'bg-amber-500/10 text-amber-700 dark:text-amber-300'}`}>{attempt.status}</span></td><td className="px-6 py-4">{['failed', 'cancelled'].includes(attempt.status) || attempt.checkoutStatus === 'payment_failed' ? <Link className="font-bold text-brand-primary dark:text-brand-action" to={`/checkout/${attempt.checkoutId}/payment`}>Retry</Link> : '—'}</td></tr>)}{!attempts.length && <tr><td className="px-6 py-10 text-center text-app-muted" colSpan={6}>No payment-gateway attempts recorded.</td></tr>}</tbody></table></div></article>;
}
