import { Download, FileUp } from 'lucide-react';
import { type FormEvent, useState } from 'react';
import { toast } from 'sonner';

import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface Props { databaseId: string; databaseName: string; engine: 'mysql' | 'postgresql'; workspacePublicId: number }
interface StagedUpload { expiresAt: string; format: string; name: string; size: number; uploadToken: string }
interface ApiBody<T> { data?: T; message: string; status: boolean }

/** Two-step native database import and direct native export controls. */
export function DatabaseTransfers({ databaseId, databaseName, engine, workspacePublicId }: Props) {
	const [file, setFile] = useState<File>(); const [staged, setStaged] = useState<StagedUpload>(); const [busy, setBusy] = useState(false); const basePath = `/api/v1/workspaces/${workspacePublicId}/databases/${databaseId}`;
	async function stage(): Promise<void> { if (!file) return; setBusy(true); try { const form = new FormData(); form.append('file', file); const response = await authenticatedFetch(`${basePath}/import/upload`, { method: 'POST', body: form }); const body = await response.json() as ApiBody<StagedUpload>; if (!response.ok || !body.status || !body.data) throw new Error(body.message); setStaged(body.data); toast.success('Import file verified and staged.'); } catch (error) { toast.error(error instanceof Error ? error.message : 'Upload failed.'); } finally { setBusy(false); } }
	async function execute(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!staged) return; setBusy(true); const values = new FormData(event.currentTarget); try { const response = await authenticatedFetch(`${basePath}/import`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ confirmation: values.get('confirmation'), mode: values.get('mode'), uploadToken: staged.uploadToken }) }); const body = await response.json() as ApiBody<unknown>; if (!response.ok || !body.status) throw new Error(body.message); toast.success('Database import completed.'); setStaged(undefined); setFile(undefined); } catch (error) { toast.error(error instanceof Error ? error.message : 'Import failed.'); } finally { setBusy(false); } }
	async function download(): Promise<void> { setBusy(true); try { const response = await authenticatedFetch(`${basePath}/export`); if (!response.ok) { const body = await response.json() as ApiBody<never>; throw new Error(body.message); } const blob = await response.blob(); const href = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = href; anchor.download = response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1] ?? `${databaseName}.${engine === 'postgresql' ? 'dump' : 'sql'}`; anchor.click(); URL.revokeObjectURL(href); } catch (error) { toast.error(error instanceof Error ? error.message : 'Export failed.'); } finally { setBusy(false); } }
	const input = 'mt-2 w-full rounded-xl border border-brand-primary/15 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100';
	return <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5"><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Portable copy</p><h2 className="mt-1 text-2xl font-black">Export Database</h2><p className="mt-2 text-sm text-app-muted">Downloads a native {engine === 'postgresql' ? 'PostgreSQL custom dump' : 'MySQL SQL dump'}. It is not retained by GhostDeploy.</p><button className="mt-6 inline-flex items-center gap-2 rounded-xl bg-brand-action px-5 py-3 font-bold text-brand-ink disabled:opacity-50" disabled={busy} onClick={() => void download()} type="button"><Download className="size-4" />Download Export</button></article><article className="rounded-2xl border border-red-500/20 bg-app-surface p-5"><p className="text-sm font-semibold text-red-600 dark:text-red-300">Changes database contents</p><h2 className="mt-1 text-2xl font-black">Import Database</h2><p className="mt-2 text-sm text-app-muted">Accepts {engine === 'postgresql' ? 'PostgreSQL custom dumps or plain SQL' : 'MySQL plain SQL'}. Create a recovery backup first.</p>{!staged ? <div className="mt-5"><label className="block text-sm font-semibold">Import file<input accept={engine === 'postgresql' ? '.dump,.backup,.sql' : '.sql'} className={input} onChange={(event) => setFile(event.target.files?.[0])} type="file" /></label><button className="mt-4 inline-flex items-center gap-2 rounded-xl border border-brand-primary/15 px-5 py-3 font-bold disabled:opacity-50" disabled={busy || !file} onClick={() => void stage()} type="button"><FileUp className="size-4" />Verify and Stage</button></div> : <form className="mt-5" onSubmit={(event) => void execute(event)}><div className="rounded-xl border border-brand-primary/10 p-4 text-sm"><strong>{staged.name}</strong><p className="mt-1 text-app-muted">{staged.format} · {(staged.size / 1048576).toFixed(2)} MB · expires {new Date(staged.expiresAt).toLocaleTimeString()}</p></div><fieldset className="mt-4"><legend className="text-sm font-semibold">Import mode</legend><label className="mt-2 flex gap-2 text-sm"><input defaultChecked name="mode" type="radio" value="merge" />Apply without automatic cleanup</label><label className="mt-2 flex gap-2 text-sm"><input name="mode" type="radio" value="replace" />{engine === 'postgresql' ? 'Clean and replace matching objects' : 'Apply dump replacement instructions'} (destructive)</label></fieldset><label className="mt-4 block text-sm font-semibold">Type <strong>{databaseName}</strong> to confirm<input className={input} name="confirmation" required /></label><div className="mt-5 flex flex-wrap gap-3"><button className="rounded-xl bg-red-600 px-5 py-3 font-bold text-white disabled:opacity-50" disabled={busy} type="submit">Run Import</button><button className="rounded-xl border border-brand-primary/15 px-5 py-3 font-bold" onClick={() => setStaged(undefined)} type="button">Cancel</button></div></form>}</article></section>;
}
