import { CalendarClock, CheckCircle2, Copy, Download, HardDriveDownload, RotateCcw, Trash2 } from 'lucide-react';
import { type FormEvent, useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router';
import { toast } from 'sonner';

import { DestructiveConfirmation, type DestructiveConfirmationValue } from '@components/ui/destructive-confirmation';
import { authenticatedFetch } from '@root/app/utils/authenticatedFetch';

interface BackupRecord { createdAt: string; expiresAt: string; failureReason?: string | null; id: string; lastRestoredAt?: string | null; lastVerifiedAt?: string | null; sizeBytes?: number | null; status: string; storageProvider: 'local' | 's3'; trigger: 'manual' | 'scheduled'; verificationFailureReason?: string | null; verificationStatus: string }
interface BackupSchedule { frequencyHours: number; isEnabled: boolean; lastFailureReason?: string | null; lastRunAt?: string | null; nextRunAt: string; retentionDays: number }
interface DatabaseOption { databaseName: string; engine: string; id: string }
interface ApiBody<T> { data?: T; message: string; status: boolean }
interface Props { databaseId: string; databaseName: string; workspacePublicId: number }

async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await authenticatedFetch(path, init); const body = await response.json() as ApiBody<T>; if (!response.ok || !body.status || body.data === undefined) throw new Error(body.message); return body.data; }

/** Customer controls for manual and scheduled encrypted logical-database recovery points. */
export function DatabaseBackups({ databaseId, databaseName, workspacePublicId }: Props) {
	const location = useLocation(); const navigate = useNavigate(); const [backups, setBackups] = useState<BackupRecord[]>([]); const [databases, setDatabases] = useState<DatabaseOption[]>([]); const [schedule, setSchedule] = useState<BackupSchedule | null>(null); const [submitting, setSubmitting] = useState(false);
	const query = new URLSearchParams(location.search); const selectedBackupId = query.get('backup'); const action = query.get('action'); const selectedBackup = backups.find(({ id }) => id === selectedBackupId); const basePath = `/api/v1/workspaces/${workspacePublicId}/databases/${databaseId}/backups`;
	const load = useCallback(async () => { try { const [history, policy, options] = await Promise.all([api<BackupRecord[]>(basePath), api<BackupSchedule | null>(`${basePath}/schedule`), api<DatabaseOption[]>(`/api/v1/workspaces/${workspacePublicId}/databases`)]); setBackups(history); setSchedule(policy); setDatabases(options); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load backups.'); } }, [basePath, workspacePublicId]);
	useEffect(() => { const timeout = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timeout); }, [load]);
	async function create(): Promise<void> { setSubmitting(true); try { await api<BackupRecord>(basePath, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); toast.success('Database backup completed.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Backup failed.'); } finally { setSubmitting(false); } }
	async function saveSchedule(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); const form = new FormData(event.currentTarget); setSubmitting(true); try { await api(`${basePath}/schedule`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ frequencyHours: Number(form.get('frequencyHours')), retentionDays: Number(form.get('retentionDays')), isEnabled: form.get('isEnabled') === 'on' }) }); toast.success('Backup schedule saved.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save schedule.'); } finally { setSubmitting(false); } }
	async function restore(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!selectedBackupId) return; setSubmitting(true); try { const confirmation = new FormData(event.currentTarget).get('confirmation'); await api(`${basePath}/${selectedBackupId}/restore`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ confirmation }) }); toast.success('Database restored.'); navigate(`/dashboard/databases/${databaseId}/backups`, { replace: true }); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Restore failed.'); } finally { setSubmitting(false); } }
	async function clone(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!selectedBackupId) return; const form = new FormData(event.currentTarget); setSubmitting(true); try { await api(`${basePath}/${selectedBackupId}/clone`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetDatabaseId: form.get('targetDatabaseId'), confirmation: form.get('confirmation') }) }); toast.success('Backup cloned to the selected database.'); navigate(`/dashboard/databases/${databaseId}/backups`, { replace: true }); } catch (error) { toast.error(error instanceof Error ? error.message : 'Clone failed.'); } finally { setSubmitting(false); } }
	async function verify(backupId: string): Promise<void> { setSubmitting(true); try { await api(`${basePath}/${backupId}/verify`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); toast.success('Backup integrity verified.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Verification failed.'); } finally { setSubmitting(false); } }
	async function remove(backupId: string, confirmation: DestructiveConfirmationValue): Promise<void> { setSubmitting(true); try { await api(`${basePath}/${backupId}`, { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify(confirmation) }); toast.success('Backup deleted.'); navigate(`/dashboard/databases/${databaseId}/backups`, { replace: true }); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Delete failed.'); } finally { setSubmitting(false); } }
	async function download(backupId: string): Promise<void> { setSubmitting(true); try { const response = await authenticatedFetch(`${basePath}/${backupId}/download`); if (!response.ok) { const body = await response.json() as ApiBody<never>; throw new Error(body.message); } const blob = await response.blob(); const href = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = href; anchor.download = response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1] ?? `database-backup-${backupId}`; anchor.click(); URL.revokeObjectURL(href); } catch (error) { toast.error(error instanceof Error ? error.message : 'Download failed.'); } finally { setSubmitting(false); } }
	const cloneTargets = databases.filter(({ id }) => id !== databaseId);
	return <section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-primary dark:text-brand-action">Recovery</p><h3 className="mt-1 text-2xl font-black">Backups</h3></div><button className="inline-flex items-center gap-2 rounded-xl bg-brand-action px-4 py-3 font-bold text-brand-ink" disabled={submitting} onClick={() => void create()} type="button"><HardDriveDownload className="size-4" />Create Backup</button></div>
		<form className="mt-5 grid gap-4 rounded-2xl border border-brand-primary/10 bg-app-surface p-5 sm:grid-cols-4 sm:items-end" onSubmit={(event) => void saveSchedule(event)}><div className="sm:col-span-4"><p className="flex items-center gap-2 font-bold"><CalendarClock className="size-4" />Automatic Backups</p><p className="mt-1 text-sm text-app-muted">The platform worker creates encrypted recovery points and removes artifacts after retention expires.</p></div><label className="grid gap-2 text-sm font-semibold">Every<input className="rounded-xl border border-brand-primary/15 bg-app-bg px-4 py-3" defaultValue={schedule?.frequencyHours ?? 24} min="1" name="frequencyHours" required type="number" /><span className="text-xs font-normal text-app-muted">Hours</span></label><label className="grid gap-2 text-sm font-semibold">Retain<input className="rounded-xl border border-brand-primary/15 bg-app-bg px-4 py-3" defaultValue={schedule?.retentionDays ?? 7} min="1" name="retentionDays" required type="number" /><span className="text-xs font-normal text-app-muted">Days, limited by package</span></label><label className="flex items-center gap-3 rounded-xl border border-brand-primary/15 px-4 py-3 text-sm font-semibold"><input defaultChecked={schedule?.isEnabled ?? true} name="isEnabled" type="checkbox" />Enabled</label><button className="rounded-xl bg-brand-action px-4 py-3 font-bold text-brand-ink" disabled={submitting} type="submit">Save Schedule</button>{schedule && <p className="text-xs text-app-muted sm:col-span-4">Next run {new Date(schedule.nextRunAt).toLocaleString()}{schedule.lastRunAt ? ` · Last run ${new Date(schedule.lastRunAt).toLocaleString()}` : ''}{schedule.lastFailureReason ? ` · ${schedule.lastFailureReason}` : ''}</p>}</form>
		<div className="mt-5 grid gap-3">{backups.map((backup) => <article className="rounded-2xl border border-brand-primary/10 bg-app-surface p-5" key={backup.id}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="font-bold capitalize">{backup.status} {backup.trigger} backup</p><p className="mt-1 text-sm text-app-muted">{new Date(backup.createdAt).toLocaleString()} · {backup.sizeBytes ? `${(backup.sizeBytes / 1048576).toFixed(2)} MB` : 'Size pending'} · {backup.storageProvider === 's3' ? 'Off-site' : 'Local'} · expires {new Date(backup.expiresAt).toLocaleDateString()}</p><p className="mt-1 text-xs text-app-muted">Integrity: {backup.verificationStatus}{backup.lastVerifiedAt ? ` on ${new Date(backup.lastVerifiedAt).toLocaleString()}` : ''}</p></div>{backup.status === 'completed' && <div className="flex flex-wrap gap-2"><button aria-label="Verify backup" className="rounded-lg border border-brand-primary/15 p-2" disabled={submitting} onClick={() => void verify(backup.id)} type="button"><CheckCircle2 className="size-4" /></button><button aria-label="Download backup" className="rounded-lg border border-brand-primary/15 p-2" disabled={submitting} onClick={() => void download(backup.id)} type="button"><Download className="size-4" /></button><button className="inline-flex items-center gap-2 rounded-lg border border-brand-primary/15 px-3 py-2 text-sm font-bold" disabled={submitting || !cloneTargets.length} onClick={() => navigate(`/dashboard/databases/${databaseId}/backups?backup=${backup.id}&action=clone`)} type="button"><Copy className="size-4" />Clone</button><button className="inline-flex items-center gap-2 rounded-lg border border-brand-primary/15 px-3 py-2 text-sm font-bold" disabled={submitting} onClick={() => navigate(`/dashboard/databases/${databaseId}/backups?backup=${backup.id}&action=restore`)} type="button"><RotateCcw className="size-4" />Restore</button><button aria-label="Delete backup" className="rounded-lg border border-red-500/30 p-2 text-red-600 dark:text-red-400" disabled={submitting} onClick={() => navigate(`/dashboard/databases/${databaseId}/backups?backup=${backup.id}&action=delete`)} type="button"><Trash2 className="size-4" /></button></div>}</div>{(backup.failureReason || backup.verificationFailureReason) && <p className="mt-3 text-sm text-red-600 dark:text-red-400">{backup.failureReason ?? backup.verificationFailureReason}</p>}</article>)}{!backups.length && <p className="rounded-2xl border border-dashed border-brand-primary/20 p-6 text-center text-sm text-app-muted">No backups yet.</p>}</div>
		{action === 'restore' && selectedBackupId && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><form className="w-full max-w-lg rounded-3xl bg-app-surface p-6 shadow-2xl" onSubmit={(event) => void restore(event)}><h3 className="text-2xl font-black">Restore Database</h3><p className="mt-3 text-sm text-app-muted">This overwrites the current contents. Type <strong className="text-app-text">{databaseName}</strong> to confirm.</p><input autoFocus className="mt-5 w-full rounded-xl border border-brand-primary/15 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100" name="confirmation" required /><div className="mt-5 flex justify-end gap-3"><button className="rounded-xl border border-brand-primary/15 px-4 py-2 font-bold" onClick={() => navigate(`/dashboard/databases/${databaseId}/backups`)} type="button">Cancel</button><button className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white" disabled={submitting} type="submit">Restore and Overwrite</button></div></form></div>}
		{action === 'clone' && selectedBackupId && <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4"><form className="w-full max-w-lg rounded-3xl bg-app-surface p-6 shadow-2xl" onSubmit={(event) => void clone(event)}><h3 className="text-2xl font-black">Clone Backup</h3><p className="mt-2 text-sm text-app-muted">Restore this backup into another database of the same engine. The target contents will be overwritten.</p><label className="mt-5 grid gap-2 text-sm font-semibold">Target Database<select className="rounded-xl border border-brand-primary/15 bg-app-bg px-4 py-3" name="targetDatabaseId" required>{cloneTargets.map((database) => <option key={database.id} value={database.id}>{database.databaseName} · {database.engine}</option>)}</select></label><label className="mt-4 grid gap-2 text-sm font-semibold">Type the target database name<input className="rounded-xl border border-brand-primary/15 bg-app-bg px-4 py-3" name="confirmation" required /></label><div className="mt-5 flex justify-end gap-3"><button className="rounded-xl border border-brand-primary/15 px-4 py-2 font-bold" onClick={() => navigate(`/dashboard/databases/${databaseId}/backups`)} type="button">Cancel</button><button className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white" disabled={submitting} type="submit">Clone and Overwrite</button></div></form></div>}
		{action === 'delete' && selectedBackup && <DestructiveConfirmation busy={submitting} description="This permanently removes the encrypted backup artifact. It cannot be restored afterward." onCancel={() => navigate(`/dashboard/databases/${databaseId}/backups`, { replace: true })} onConfirm={(confirmation) => remove(selectedBackup.id, confirmation)} resourceName={`backup-${selectedBackup.id.slice(0, 8)}`} title="Delete Database Backup" />}</section>;
}
