import {
	index,
	layout,
	prefix,
	route,
	type RouteConfig,
} from '@react-router/dev/routes';

export default [
	index('pages/website/home.tsx'),
	route('login', 'pages/auth/login.tsx'),
	route('login/verify/:challengeId', 'pages/auth/verify.tsx'),
	route('checkout/:packageSlug/:priceId', 'pages/customer/checkout.tsx'),
	route('checkout/:checkoutId/payment', 'pages/customer/checkout-payment.tsx'),
	route('checkout/:checkoutId/failed', 'pages/customer/checkout-failed.tsx'),
	route('checkout/:checkoutId/setup', 'pages/customer/checkout-setup.tsx'),
	layout('layouts/customer.tsx', [
		route('dashboard', 'pages/customer/overview.tsx'),
		route('dashboard/subscription', 'pages/customer/subscription.tsx'),
		route('dashboard/billing', 'pages/customer/billing.tsx'),
		route('dashboard/security', 'pages/customer/security.tsx'),
		route('dashboard/workspaces/create', 'pages/customer/create-workspace-modal.tsx'),
	]),
	layout('layouts/application.tsx', [
		route('admin/overview', 'pages/admin/overview.tsx'),
		route('admin/packages', 'pages/admin/packages.tsx'),
		route('admin/packages/create', 'pages/admin/packages-create.tsx'),
		route('admin/packages/:packageSlug/:section', 'pages/admin/package-detail.tsx'),
		route('admin/offers', 'pages/admin/offers.tsx'),
		route('admin/offers/create', 'pages/admin/offers-create.tsx'),
		route('admin/offers/:offerSlug', 'pages/admin/offer-detail.tsx'),
		route('admin/offers/:offerSlug/edit', 'pages/admin/offer-edit.tsx'),
		route(
			'admin/packages/:packageSlug/edit/:section',
			'pages/admin/package-edit.tsx',
		),
		route('admin/administrators', 'pages/admin/admins.tsx'),
		route('admin/operations/payments', 'pages/admin/operations.tsx'),
		route('admin/operations/provisioning', 'pages/admin/operations-provisioning.tsx'),
		route('admin/operations/providers', 'pages/admin/operations-providers.tsx'),
		route('admin/operations/database-clusters', 'pages/admin/database-clusters.tsx'),
		route('admin/operations/database-clusters/create', 'pages/admin/database-cluster-create.tsx'),
		route('admin/operations/database-clusters/:clusterCode', 'pages/admin/database-cluster-detail.tsx'),
		route('admin/operations/database-clusters/:clusterCode/:section', 'pages/admin/database-cluster-section.tsx'),
		route(
			'admin/administrators/create',
			'pages/admin/administrators-create.tsx',
		),
		route(
			'admin/administrators/create/:section',
			'pages/admin/administrator-create-section.tsx',
		),
		route(
			'admin/administrators/:adminId',
			'pages/admin/administrator-detail.tsx',
		),
		route(
			'admin/administrators/:adminId/:section',
			'pages/admin/administrator-section.tsx',
		),
		route(
			'admin/administrators/:adminId/edit/:section',
			'pages/admin/administrator-edit-section.tsx',
		),
		layout('layouts/settings.tsx', [
			route('settings/profile', 'pages/account/profile.tsx'),
			route('settings/security', 'pages/account/security.tsx'),
			route('settings/sessions', 'pages/account/sessions.tsx'),
			route('settings/sessions/:sessionId', 'pages/account/session-detail.tsx'),
		]),
		route('search/:query', 'pages/search.tsx'),
	]),
	route('api/docs', 'pages/api/docs.tsx'),
	...prefix('api/v1', [
		route('health', 'api/v1/health.ts'),
		route('openapi.json', 'api/v1/openapi.ts'),
		route('auth/otp/request', 'api/v1/auth/otp-request.ts'),
		route('auth/otp/verify', 'api/v1/auth/otp-verify.ts'),
		route('auth/refresh', 'api/v1/auth/refresh.ts'),
		route('auth/logout', 'api/v1/auth/logout.ts'),
		route('auth/context', 'api/v1/auth/context.ts'),
		route('auth/sessions', 'api/v1/auth/sessions.ts'),
		route('auth/sessions/others', 'api/v1/auth/sessions-others.ts'),
		route('auth/sessions/:sessionId', 'api/v1/auth/session.ts'),
		route('workspaces', 'api/v1/workspaces/index.ts'),
		route('workspaces/:workspaceId', 'api/v1/workspaces/detail.ts'),
		route('workspaces/:workspaceId/resources', 'api/v1/workspaces/resources.ts'),
		route('checkouts', 'api/v1/checkouts/index.ts'),
		route('checkouts/:checkoutId', 'api/v1/checkouts/detail.ts'),
		route('checkouts/:checkoutId/payment', 'api/v1/payments/initiate.ts'),
		route('payments/providers', 'api/v1/payments/providers.ts'),
		route('payments/payu/callback', 'api/v1/payments/payu-callback.ts'),
		route('payments/:provider/callback', 'api/v1/payments/provider-callback.ts'),
		route('webhooks/payments/:provider', 'api/v1/payments/provider-webhook.ts'),
		route('internal/jobs/process', 'api/v1/internal/jobs.ts'),
		route('internal/provider/health', 'api/v1/internal/provider-health.ts'),
		route('operations/payments', 'api/v1/operations/payments.ts'),
		route('operations/provisioning', 'api/v1/operations/jobs.ts'),
		route('operations/provisioning/:jobId/retry', 'api/v1/operations/job-retry.ts'),
		route('operations/provider/health', 'api/v1/operations/provider-health.ts'),
		route('operations/database-clusters', 'api/v1/operations/database-clusters/index.ts'),
		route('operations/database-clusters/:clusterCode', 'api/v1/operations/database-clusters/detail.ts'),
		route('operations/database-clusters/:clusterCode/validate', 'api/v1/operations/database-clusters/validate.ts'),
		route('operations/database-clusters/:clusterCode/backups', 'api/v1/operations/database-clusters/backups.ts'),
		route('admins', 'api/v1/admins/index.ts'),
		route('admins/options', 'api/v1/admins/options.ts'),
		route('admins/:adminId', 'api/v1/admins/detail.ts'),
		route('admins/:adminId/roles', 'api/v1/admins/roles.ts'),
		route('admins/:adminId/overrides', 'api/v1/admins/overrides.ts'),
		route('packages', 'api/v1/packages/index.ts'),
		route('packages/:packageSlug', 'api/v1/packages/detail.ts'),
		route('packages/:packageSlug/prices', 'api/v1/packages/prices.ts'),
		route('packages/:packageSlug/prices/:priceId', 'api/v1/packages/price-detail.ts'),
		route('packages/:packageSlug/cost-reviews', 'api/v1/packages/cost-reviews.ts'),
		route('packages/:packageSlug/entitlements', 'api/v1/packages/entitlements.ts'),
		route('package-categories', 'api/v1/package-categories/index.ts'),
		route('offers', 'api/v1/offers/index.ts'),
		route('offers/:offerSlug', 'api/v1/offers/detail.ts'),
		route('public/catalogue', 'api/v1/public/catalogue.ts'),
		route('public/checkout-quotes', 'api/v1/public/checkout-quote.ts'),
	]),
	route('api/*', 'pages/api/catchall.ts'),
	route('*', 'pages/website/not-found.tsx'),
] satisfies RouteConfig;
