import { and, asc, desc, eq, inArray, isNull, sql } from 'drizzle-orm';
import { resp } from '@qubitcodes/qcresp';

import { db } from '@db/client';
import { applicationBuilds, applicationCronJobs, applicationDatabaseBindings, applicationDeployments, applicationDomains, authenticationEvents, customers, databaseClusters, logicalDatabases, packages, platformRoles, platformUserRoles, runtimeImages, userSessions, users, workspaceGithubConnections, workspaceMemberships, workspaceResources, workspaces, workspaceSubscriptions } from '@db/schema';
import { recordRequiredAdminAuditLog } from '@services/auditLogService';
import { authorizeAdmin, type AuthorizedAdmin } from '@services/authorization/adminAuthorizationService';
import type { RequestMetadata } from '@utils/request';

function can(actor: AuthorizedAdmin, code: string): boolean { return actor.isSuperAdmin || actor.permissionCodes.has(code); }
async function audit(actor: AuthorizedAdmin, action: string, resourceType: string, resourceId: string | undefined, metadata: RequestMetadata, details: Record<string, unknown> = {}, reason?: string): Promise<void> { await recordRequiredAdminAuditLog({ actorUserId: actor.userId, action, resourceType, resourceId, reason, metadata: { permission: action.replace(/^admin\./, ''), ...details }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); }
function visibleAdminTarget(actor: AuthorizedAdmin) { return sql<boolean>`(${users.id} = ${actor.userId} OR NOT EXISTS (SELECT 1 FROM ${platformUserRoles} INNER JOIN ${platformRoles} ON ${platformRoles.id} = ${platformUserRoles.roleId} WHERE ${platformUserRoles.userId} = ${users.id} AND ${platformRoles.isSuperAdmin} = true AND ${platformUserRoles.deletedAt} IS NULL AND ${platformRoles.deletedAt} IS NULL))`; }

/** User-centric administrator control plane. Every successful read and mutation is durably audited. */
export class AdminCustomerControlController {
	public static async index(request: Request, metadata: RequestMetadata): Promise<Response> {
		try {
			const actor = await authorizeAdmin(request, 'customers.view', metadata);
			const rows = await db.select({ id: users.id, publicId: users.publicId, displayName: users.displayName, countryCode: users.countryCode, mobile: users.mobile, status: users.status, mobileVerifiedAt: users.mobileVerifiedAt, createdAt: users.createdAt, customerPublicId: customers.publicId, workspaceCount: sql<number>`count(distinct ${workspaceMemberships.workspaceId})`, lastActiveAt: sql<Date | null>`max(${userSessions.lastActiveAt})` }).from(users).leftJoin(customers, and(eq(customers.userId, users.id), isNull(customers.deletedAt))).leftJoin(workspaceMemberships, and(eq(workspaceMemberships.customerId, customers.id), isNull(workspaceMemberships.deletedAt))).leftJoin(userSessions, and(eq(userSessions.userId, users.id), isNull(userSessions.deletedAt))).where(and(isNull(users.deletedAt), visibleAdminTarget(actor))).groupBy(users.id, customers.publicId).orderBy(desc(users.createdAt));
			await audit(actor, 'admin.customers.view', 'user_collection', undefined, metadata, { resultCount: rows.length });
			return resp.success('Users retrieved.', rows);
		} catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); }
	}

	public static async show(request: Request, publicId: number, metadata: RequestMetadata): Promise<Response> {
		try {
			const actor = await authorizeAdmin(request, 'customers.view', metadata);
			const [user] = await db.select({ id: users.id, publicId: users.publicId, displayName: users.displayName, countryCode: users.countryCode, mobile: users.mobile, status: users.status, mobileVerifiedAt: users.mobileVerifiedAt, tokenVersion: users.tokenVersion, createdAt: users.createdAt, customerId: customers.id, customerPublicId: customers.publicId, onboardingStatus: customers.onboardingStatus }).from(users).leftJoin(customers, and(eq(customers.userId, users.id), isNull(customers.deletedAt))).where(and(eq(users.publicId, publicId), isNull(users.deletedAt), visibleAdminTarget(actor))).limit(1);
			if (!user) return resp.failure('User not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404);
			const memberships = user.customerId ? await db.select({ workspaceId: workspaces.id, workspacePublicId: workspaces.publicId, workspaceName: workspaces.name, workspaceType: workspaces.type, workspaceStatus: workspaces.status, role: workspaceMemberships.role, membershipStatus: workspaceMemberships.status, packageName: packages.name, subscriptionStatus: workspaceSubscriptions.status, termEndsAt: workspaceSubscriptions.termEndsAt }).from(workspaceMemberships).innerJoin(workspaces, and(eq(workspaces.id, workspaceMemberships.workspaceId), isNull(workspaces.deletedAt))).leftJoin(workspaceSubscriptions, and(eq(workspaceSubscriptions.workspaceId, workspaces.id), eq(workspaceSubscriptions.isPrimary, true), isNull(workspaceSubscriptions.deletedAt))).leftJoin(packages, eq(packages.id, workspaceSubscriptions.packageId)).where(and(eq(workspaceMemberships.customerId, user.customerId), isNull(workspaceMemberships.deletedAt))).orderBy(asc(workspaces.name)) : [];
			const sessions = can(actor, 'user_sessions.view') ? await db.select({ id: userSessions.id, deviceLabel: userSessions.deviceLabel, deviceType: userSessions.deviceType, browserName: userSessions.browserName, osName: userSessions.osName, ipAddress: userSessions.ipAddress, location: userSessions.location, activeContextType: userSessions.activeContextType, signedInAt: userSessions.signedInAt, lastActiveAt: userSessions.lastActiveAt, expiresAt: userSessions.expiresAt, revokedAt: userSessions.revokedAt, revokeReason: userSessions.revokeReason }).from(userSessions).where(and(eq(userSessions.userId, user.id), isNull(userSessions.deletedAt))).orderBy(desc(userSessions.lastActiveAt)).limit(100) : undefined;
			const authentication = can(actor, 'authentication_events.view') ? await db.select({ id: authenticationEvents.id, type: authenticationEvents.type, status: authenticationEvents.status, reason: authenticationEvents.reason, ipAddress: authenticationEvents.ipAddress, createdAt: authenticationEvents.createdAt }).from(authenticationEvents).where(and(eq(authenticationEvents.userId, user.id), isNull(authenticationEvents.deletedAt))).orderBy(desc(authenticationEvents.createdAt)).limit(100) : undefined;
			await audit(actor, 'admin.customers.view', 'user', user.id, metadata, { customerPublicId: user.customerPublicId, publicId });
			if (sessions) await audit(actor, 'admin.user_sessions.view', 'user', user.id, metadata, { resultCount: sessions.length });
			if (authentication) await audit(actor, 'admin.authentication_events.view', 'user', user.id, metadata, { resultCount: authentication.length });
			return resp.success('User control record retrieved.', { user, workspaces: memberships, sessions, authentication, permissions: { canSuspend: can(actor, 'customers.suspend'), canRevokeSessions: can(actor, 'user_sessions.revoke') } });
		} catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); }
	}

	public static async workspace(request: Request, publicId: number, workspacePublicId: number, metadata: RequestMetadata): Promise<Response> {
		try {
			const actor = await authorizeAdmin(request, 'customers.view', metadata);
			const [workspace] = await db.select({ id: workspaces.id, publicId: workspaces.publicId, name: workspaces.name, type: workspaces.type, status: workspaces.status, ownerUserPublicId: users.publicId }).from(workspaces).innerJoin(workspaceMemberships, and(eq(workspaceMemberships.workspaceId, workspaces.id), isNull(workspaceMemberships.deletedAt))).innerJoin(customers, and(eq(customers.id, workspaceMemberships.customerId), isNull(customers.deletedAt))).innerJoin(users, and(eq(users.id, customers.userId), eq(users.publicId, publicId), isNull(users.deletedAt))).where(and(eq(workspaces.publicId, workspacePublicId), isNull(workspaces.deletedAt), visibleAdminTarget(actor))).limit(1);
			if (!workspace) return resp.failure('Workspace not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404);
			const applications = can(actor, 'applications.view') ? await db.select({ id: applicationBuilds.id, name: workspaceResources.name, status: workspaceResources.status, publicUrl: workspaceResources.publicUrl, provider: workspaceResources.provider, providerResourceId: workspaceResources.providerResourceId, framework: applicationBuilds.framework, environment: applicationBuilds.deploymentEnvironment, repository: applicationBuilds.sourceRepository, branch: applicationBuilds.sourceRef, baseDirectory: applicationBuilds.baseDirectory, publishDirectory: applicationBuilds.publishDirectory, port: applicationBuilds.applicationPort, runtimeCode: runtimeImages.code, stack: runtimeImages.language, version: runtimeImages.version, createdAt: applicationBuilds.createdAt }).from(applicationBuilds).innerJoin(runtimeImages, eq(runtimeImages.id, applicationBuilds.runtimeImageId)).leftJoin(workspaceResources, eq(workspaceResources.id, applicationBuilds.resourceId)).where(and(eq(applicationBuilds.workspaceId, workspace.id), isNull(applicationBuilds.deletedAt))).orderBy(desc(applicationBuilds.createdAt)) : [];
			const appIds = applications.map(({ id }) => id);
			const [domains, crons, deployments, databaseBindings, databases, gitConnections] = await Promise.all([
				can(actor, 'domains.view') && appIds.length ? db.select().from(applicationDomains).where(and(inArray(applicationDomains.applicationBuildId, appIds), isNull(applicationDomains.deletedAt))) : [],
				can(actor, 'cron_jobs.view') && appIds.length ? db.select({ id: applicationCronJobs.id, applicationBuildId: applicationCronJobs.applicationBuildId, name: applicationCronJobs.name, command: applicationCronJobs.command, frequency: applicationCronJobs.frequency, timeoutSeconds: applicationCronJobs.timeoutSeconds, isEnabled: applicationCronJobs.isEnabled, syncStatus: applicationCronJobs.syncStatus, lastSyncError: applicationCronJobs.lastSyncError }).from(applicationCronJobs).where(and(inArray(applicationCronJobs.applicationBuildId, appIds), isNull(applicationCronJobs.deletedAt))) : [],
				can(actor, 'deployments.view') && appIds.length ? db.select({ id: applicationDeployments.id, applicationBuildId: applicationDeployments.applicationBuildId, status: applicationDeployments.status, providerDeploymentId: applicationDeployments.providerDeploymentId, failureReason: applicationDeployments.failureReason, createdAt: applicationDeployments.createdAt, completedAt: applicationDeployments.completedAt }).from(applicationDeployments).where(and(inArray(applicationDeployments.applicationBuildId, appIds), isNull(applicationDeployments.deletedAt))).orderBy(desc(applicationDeployments.createdAt)).limit(200) : [],
				can(actor, 'databases.view') && appIds.length ? db.select({ applicationBuildId: applicationDatabaseBindings.applicationBuildId, databaseId: logicalDatabases.id, databaseName: logicalDatabases.databaseName, username: logicalDatabases.username, status: logicalDatabases.status, engine: databaseClusters.engine, engineVersion: databaseClusters.engineVersion }).from(applicationDatabaseBindings).innerJoin(logicalDatabases, eq(logicalDatabases.id, applicationDatabaseBindings.logicalDatabaseId)).innerJoin(databaseClusters, eq(databaseClusters.id, logicalDatabases.clusterId)).where(and(inArray(applicationDatabaseBindings.applicationBuildId, appIds), isNull(applicationDatabaseBindings.deletedAt), isNull(logicalDatabases.deletedAt))) : [],
				can(actor, 'databases.view') ? db.select({ id: logicalDatabases.id, databaseName: logicalDatabases.databaseName, username: logicalDatabases.username, status: logicalDatabases.status, storageQuotaMb: logicalDatabases.storageQuotaMb, connectionLimit: logicalDatabases.connectionLimit, lastBackedUpAt: logicalDatabases.lastBackedUpAt, engine: databaseClusters.engine, engineVersion: databaseClusters.engineVersion }).from(logicalDatabases).innerJoin(databaseClusters, eq(databaseClusters.id, logicalDatabases.clusterId)).where(and(eq(logicalDatabases.workspaceId, workspace.id), isNull(logicalDatabases.deletedAt))) : [],
				can(actor, 'git_connections.view') ? db.select({ id: workspaceGithubConnections.id, accountLogin: workspaceGithubConnections.accountLogin, accountName: workspaceGithubConnections.accountName, accountType: workspaceGithubConnections.accountType, status: workspaceGithubConnections.status, providerSyncStatus: workspaceGithubConnections.providerSyncStatus, providerSyncError: workspaceGithubConnections.providerSyncError, createdAt: workspaceGithubConnections.createdAt }).from(workspaceGithubConnections).where(and(eq(workspaceGithubConnections.workspaceId, workspace.id), isNull(workspaceGithubConnections.deletedAt))) : [],
			]);
			const resources = applications.map((application) => ({ ...application, domains: domains.filter((item) => item.applicationBuildId === application.id), crons: crons.filter((item) => item.applicationBuildId === application.id), deployments: deployments.filter((item) => item.applicationBuildId === application.id), databases: databaseBindings.filter((item) => item.applicationBuildId === application.id) }));
			for (const [permission, value] of [['applications.view', resources], ['domains.view', domains], ['cron_jobs.view', crons], ['deployments.view', deployments], ['databases.view', databases], ['git_connections.view', gitConnections]] as const) if (can(actor, permission)) await audit(actor, `admin.${permission}`, 'workspace', workspace.id, metadata, { resultCount: value.length, workspacePublicId });
			return resp.success('Workspace resource control record retrieved.', { workspace, applications: resources, databases, gitConnections });
		} catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); }
	}

	public static async updateStatus(request: Request, publicId: number, input: { reason: string; status: 'active' | 'inactive' | 'suspended' }, metadata: RequestMetadata): Promise<Response> {
		try { const actor = await authorizeAdmin(request, 'customers.suspend', metadata); const [user] = await db.update(users).set({ status: input.status, tokenVersion: sql`${users.tokenVersion} + 1`, updatedAt: new Date() }).where(and(eq(users.publicId, publicId), isNull(users.deletedAt), visibleAdminTarget(actor))).returning({ id: users.id, status: users.status }); if (!user) return resp.failure('User not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); if (input.status !== 'active') await db.update(userSessions).set({ revokedAt: new Date(), revokeReason: input.reason, updatedAt: new Date() }).where(and(eq(userSessions.userId, user.id), isNull(userSessions.revokedAt), isNull(userSessions.deletedAt))); await audit(actor, 'admin.customers.suspend', 'user', user.id, metadata, { status: input.status }, input.reason); return resp.success('User status updated.', user, resp.codes.UPDATED); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); }
	}

	public static async revokeSession(request: Request, publicId: number, sessionId: string, reason: string, metadata: RequestMetadata): Promise<Response> {
		try { const actor = await authorizeAdmin(request, 'user_sessions.revoke', metadata); const [session] = await db.update(userSessions).set({ revokedAt: new Date(), revokeReason: reason, updatedAt: new Date() }).where(and(eq(userSessions.id, sessionId), isNull(userSessions.revokedAt), isNull(userSessions.deletedAt), eq(userSessions.userId, db.select({ id: users.id }).from(users).where(and(eq(users.publicId, publicId), isNull(users.deletedAt), visibleAdminTarget(actor)))))).returning({ id: userSessions.id }); if (!session) return resp.failure('Active session not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await audit(actor, 'admin.user_sessions.revoke', 'user_session', session.id, metadata, { userPublicId: publicId }, reason); return resp.success('Session revoked.', session, resp.codes.UPDATED); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); }
	}
}
