import { Readable } from 'node:stream';
import { and, desc, eq, isNull, sql } from 'drizzle-orm';
import { resp } from '@qubitcodes/qcresp';

import { db } from '@db/client';
import { customers, databaseBackups, databaseBackupSchedules, databaseClusters, logicalDatabases, workspaceMemberships, workspaces, workspaceSubscriptions } from '@db/schema';
import type { CloneDatabaseBackupRequest, DatabaseBackupScheduleRequest, RestoreDatabaseBackupRequest } from '@schemas/databaseBackup';
import type { DestructiveActionRequest } from '@schemas/destructiveAction';
import { recordAuditLog } from '@services/auditLogService';
import { authenticateSession } from '@services/auth/authenticatedSessionService';
import { authenticationFailureResponse } from '@services/auth/authenticationFailureService';
import { databaseBackupService, type DatabaseBackupConnection } from '@services/databases/databaseBackupService';
import { databaseClusterEndpoint } from '@services/databases/databaseClusterEndpointService';
import { decryptCredential } from '@services/encryption/credentialEncryptionService';
import type { RequestMetadata } from '@utils/request';

interface WorkspaceAccess { actorUserId: string; entitlementSnapshot: Array<Record<string, unknown>>; id: string }

async function workspaceAccess(request: Request, publicId: number, metadata: RequestMetadata): Promise<WorkspaceAccess> {
	const actor = await authenticateSession(request, metadata);
	const [workspace] = await db.select({ id: workspaces.id, entitlementSnapshot: workspaceSubscriptions.entitlementSnapshot }).from(customers).innerJoin(workspaceMemberships, and(eq(workspaceMemberships.customerId, customers.id), eq(workspaceMemberships.status, 'active'), isNull(workspaceMemberships.deletedAt))).innerJoin(workspaces, and(eq(workspaces.id, workspaceMemberships.workspaceId), eq(workspaces.publicId, publicId), eq(workspaces.status, 'active'), isNull(workspaces.deletedAt))).innerJoin(workspaceSubscriptions, and(eq(workspaceSubscriptions.workspaceId, workspaces.id), sql`${workspaceSubscriptions.status} IN ('active', 'trialing')`, isNull(workspaceSubscriptions.deletedAt))).where(and(eq(customers.userId, actor.userId), isNull(customers.deletedAt))).limit(1);
	if (!workspace) throw new Error('Workspace not found.');
	return { actorUserId: actor.userId, id: workspace.id, entitlementSnapshot: workspace.entitlementSnapshot };
}

function entitlement(snapshot: Array<Record<string, unknown>>, code: string): Record<string, unknown> | undefined { return snapshot.find((item) => item.code === code); }
function backupsEnabled(snapshot: Array<Record<string, unknown>>): boolean { const item = entitlement(snapshot, 'backups.enabled'); return item?.booleanValue === true || Number(item?.numericValue ?? 0) > 0; }
function retentionDays(snapshot: Array<Record<string, unknown>>): number { const item = entitlement(snapshot, 'backups.retention_days'); return Math.max(1, Math.min(365, Number(item?.numericValue ?? 7))); }

async function databaseRecord(workspaceId: string, databaseId: string) {
	const [record] = await db.select({ database: logicalDatabases, cluster: databaseClusters }).from(logicalDatabases).innerJoin(databaseClusters, eq(databaseClusters.id, logicalDatabases.clusterId)).where(and(eq(logicalDatabases.id, databaseId), eq(logicalDatabases.workspaceId, workspaceId), eq(logicalDatabases.status, 'active'), isNull(logicalDatabases.deletedAt), isNull(databaseClusters.deletedAt))).limit(1);
	return record;
}

function connection(record: NonNullable<Awaited<ReturnType<typeof databaseRecord>>>): DatabaseBackupConnection {
	const credential = JSON.parse(decryptCredential(record.database.credentialCiphertext)) as DatabaseBackupConnection; const endpoint = databaseClusterEndpoint(record.cluster);
	return { ...credential, engine: record.cluster.engine, host: endpoint.host, port: endpoint.port, tlsMode: endpoint.tlsMode };
}

const publicFields = { id: databaseBackups.id, status: databaseBackups.status, restoreStatus: databaseBackups.restoreStatus, trigger: databaseBackups.trigger, storageProvider: databaseBackups.storageProvider, verificationStatus: databaseBackups.verificationStatus, lastVerifiedAt: databaseBackups.lastVerifiedAt, verificationFailureReason: databaseBackups.verificationFailureReason, checksumSha256: databaseBackups.checksumSha256, sizeBytes: databaseBackups.sizeBytes, failureReason: databaseBackups.failureReason, restoreFailureReason: databaseBackups.restoreFailureReason, startedAt: databaseBackups.startedAt, completedAt: databaseBackups.completedAt, lastRestoreStartedAt: databaseBackups.lastRestoreStartedAt, lastRestoredAt: databaseBackups.lastRestoredAt, expiresAt: databaseBackups.expiresAt, createdAt: databaseBackups.createdAt };

export async function createBackup(workspaceId: string, databaseId: string, retention: number, trigger: 'manual' | 'scheduled') {
	const record = await databaseRecord(workspaceId, databaseId); if (!record) throw new Error('Database not found.');
	const expiresAt = new Date(Date.now() + retention * 86400000); const [backup] = await db.insert(databaseBackups).values({ workspaceId, logicalDatabaseId: databaseId, expiresAt, trigger, metadata: { engine: record.cluster.engine } }).returning({ id: databaseBackups.id }); if (!backup) throw new Error('Unable to create backup record.');
	try { await db.update(databaseBackups).set({ status: 'running', startedAt: new Date(), updatedAt: new Date() }).where(eq(databaseBackups.id, backup.id)); const stored = await databaseBackupService.create(connection(record), `${workspaceId}/${databaseId}/${backup.id}.qdb`); const completedAt = new Date(); const [completed] = await db.update(databaseBackups).set({ ...stored, status: 'completed', completedAt, updatedAt: completedAt }).where(eq(databaseBackups.id, backup.id)).returning(publicFields); await db.update(logicalDatabases).set({ lastBackedUpAt: completedAt, updatedAt: completedAt }).where(eq(logicalDatabases.id, databaseId)); return completed; }
	catch (error) { const message = error instanceof Error ? error.message : 'Database backup failed.'; await db.update(databaseBackups).set({ status: 'failed', failureReason: message, updatedAt: new Date() }).where(eq(databaseBackups.id, backup.id)); throw error; }
}

/** Workspace-authorized encrypted logical database backup and restore lifecycle. */
export class DatabaseBackupController {
	public static async index(request: Request, workspacePublicId: number, databaseId: string, metadata: RequestMetadata): Promise<Response> {
		try { const workspace = await workspaceAccess(request, workspacePublicId, metadata); if (!await databaseRecord(workspace.id, databaseId)) return resp.failure('Database not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const rows = await db.select(publicFields).from(databaseBackups).where(and(eq(databaseBackups.workspaceId, workspace.id), eq(databaseBackups.logicalDatabaseId, databaseId), isNull(databaseBackups.deletedAt))).orderBy(desc(databaseBackups.createdAt)); return resp.success('Database backups retrieved.', rows); }
		catch (error) { return authenticationFailureResponse(error) ?? resp.failure('Database not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); }
	}

	public static async create(request: Request, workspacePublicId: number, databaseId: string, metadata: RequestMetadata): Promise<Response> {
		try {
			const workspace = await workspaceAccess(request, workspacePublicId, metadata); if (!backupsEnabled(workspace.entitlementSnapshot)) return resp.failure('Backups are not enabled for this workspace.', resp.codes.ORDER_CANNOT_BE_PROCESSED, undefined, null, undefined, 422); if (!await databaseRecord(workspace.id, databaseId)) return resp.failure('Database not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404);
			const completed = await createBackup(workspace.id, databaseId, retentionDays(workspace.entitlementSnapshot), 'manual'); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_created', resourceType: 'database_backup', resourceId: completed?.id, metadata: { workspacePublicId, databaseId, checksumSha256: completed?.checksumSha256, storageProvider: completed?.storageProvider }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Database backup completed.', completed, resp.codes.CREATED, undefined, 201);
		} catch (error) { const authenticationFailure = authenticationFailureResponse(error); if (authenticationFailure) return authenticationFailure; const message = error instanceof Error ? error.message : 'Database backup failed.'; return resp.failure(message, resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}

	public static async restore(request: Request, workspacePublicId: number, databaseId: string, backupId: string, input: RestoreDatabaseBackupRequest, metadata: RequestMetadata): Promise<Response> {
		try {
			const workspace = await workspaceAccess(request, workspacePublicId, metadata); const record = await databaseRecord(workspace.id, databaseId); if (!record) return resp.failure('Database not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); if (input.confirmation !== record.database.databaseName) return resp.failure('Confirmation must exactly match the database name.', resp.codes.VALIDATION_ERROR, [{ field: 'confirmation', message: 'Database name does not match.' }], null, undefined, 400); const [backup] = await db.select().from(databaseBackups).where(and(eq(databaseBackups.id, backupId), eq(databaseBackups.workspaceId, workspace.id), eq(databaseBackups.logicalDatabaseId, databaseId), eq(databaseBackups.status, 'completed'), isNull(databaseBackups.deletedAt))).limit(1); if (!backup?.storageKey || !backup.checksumSha256) return resp.failure('Backup not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404);
			const startedAt = new Date(); await db.update(databaseBackups).set({ restoreStatus: 'running', lastRestoreStartedAt: startedAt, restoreFailureReason: null, updatedAt: startedAt }).where(eq(databaseBackups.id, backup.id)); try { await databaseBackupService.restore(connection(record), backup.storageKey, backup.checksumSha256, backup.storageProvider); } catch (error) { const message = error instanceof Error ? error.message : 'Database restore failed.'; await db.update(databaseBackups).set({ restoreStatus: 'failed', restoreFailureReason: message, updatedAt: new Date() }).where(eq(databaseBackups.id, backup.id)); throw error; } const restoredAt = new Date(); await db.update(databaseBackups).set({ restoreStatus: 'completed', lastRestoredAt: restoredAt, updatedAt: restoredAt }).where(eq(databaseBackups.id, backup.id)); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_restored', resourceType: 'database_backup', resourceId: backup.id, metadata: { workspacePublicId, databaseId }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Database restored from backup.', { id: backup.id, restoredAt }, resp.codes.UPDATED);
		} catch (error) { return authenticationFailureResponse(error) ?? resp.failure(error instanceof Error ? error.message : 'Database restore failed.', resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}

	public static async download(request: Request, workspacePublicId: number, databaseId: string, backupId: string, metadata: RequestMetadata): Promise<Response> {
		try { const workspace = await workspaceAccess(request, workspacePublicId, metadata); const record = await databaseRecord(workspace.id, databaseId); const [backup] = await db.select().from(databaseBackups).where(and(eq(databaseBackups.id, backupId), eq(databaseBackups.workspaceId, workspace.id), eq(databaseBackups.logicalDatabaseId, databaseId), eq(databaseBackups.status, 'completed'), isNull(databaseBackups.deletedAt))).limit(1); if (!record || !backup?.storageKey || !backup.checksumSha256) return resp.failure('Backup not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const stream = await databaseBackupService.download(backup.storageKey, backup.checksumSha256, backup.storageProvider); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_downloaded', resourceType: 'database_backup', resourceId: backup.id, metadata: { workspacePublicId, databaseId }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return new Response(Readable.toWeb(stream) as ReadableStream, { headers: { 'content-type': 'application/octet-stream', 'content-disposition': `attachment; filename="${record.database.databaseName}-${backup.id}.${record.cluster.engine === 'postgresql' ? 'dump' : 'sql'}"`, 'cache-control': 'no-store' } }); }
		catch (error) { return authenticationFailureResponse(error) ?? resp.failure(error instanceof Error ? error.message : 'Backup download failed.', resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}

	public static async schedule(request: Request, workspacePublicId: number, databaseId: string, input: DatabaseBackupScheduleRequest | undefined, metadata: RequestMetadata): Promise<Response> {
		try {
			const workspace = await workspaceAccess(request, workspacePublicId, metadata); if (!backupsEnabled(workspace.entitlementSnapshot)) return resp.failure('Backups are not enabled for this workspace.', resp.codes.ORDER_CANNOT_BE_PROCESSED, undefined, null, undefined, 422); if (!await databaseRecord(workspace.id, databaseId)) return resp.failure('Database not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404);
			const [existing] = await db.select().from(databaseBackupSchedules).where(and(eq(databaseBackupSchedules.workspaceId, workspace.id), eq(databaseBackupSchedules.logicalDatabaseId, databaseId), isNull(databaseBackupSchedules.deletedAt))).limit(1);
			if (!input) return resp.success('Database backup schedule retrieved.', existing ?? null);
			const maximumRetention = retentionDays(workspace.entitlementSnapshot); if (input.retentionDays > maximumRetention) return resp.failure(`This package allows at most ${maximumRetention} retention days.`, resp.codes.ORDER_CANNOT_BE_PROCESSED, undefined, null, undefined, 422);
			const now = new Date(); const values = { frequencyHours: input.frequencyHours, retentionDays: input.retentionDays, isEnabled: input.isEnabled, nextRunAt: existing?.nextRunAt && existing.nextRunAt > now ? existing.nextRunAt : new Date(now.getTime() + input.frequencyHours * 3600000), updatedAt: now };
			const [saved] = existing ? await db.update(databaseBackupSchedules).set(values).where(eq(databaseBackupSchedules.id, existing.id)).returning() : await db.insert(databaseBackupSchedules).values({ ...values, workspaceId: workspace.id, logicalDatabaseId: databaseId }).returning();
			await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_schedule_saved', resourceType: 'database_backup_schedule', resourceId: saved.id, metadata: { workspacePublicId, databaseId, frequencyHours: saved.frequencyHours, retentionDays: saved.retentionDays, isEnabled: saved.isEnabled }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent });
			return resp.success('Database backup schedule saved.', saved, existing ? resp.codes.UPDATED : resp.codes.CREATED, undefined, existing ? 200 : 201);
		} catch (error) { return authenticationFailureResponse(error) ?? resp.failure(error instanceof Error ? error.message : 'Backup schedule failed.', resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}

	public static async removeSchedule(request: Request, workspacePublicId: number, databaseId: string, metadata: RequestMetadata): Promise<Response> {
		try { const workspace = await workspaceAccess(request, workspacePublicId, metadata); const [schedule] = await db.select().from(databaseBackupSchedules).where(and(eq(databaseBackupSchedules.workspaceId, workspace.id), eq(databaseBackupSchedules.logicalDatabaseId, databaseId), isNull(databaseBackupSchedules.deletedAt))).limit(1); if (!schedule) return resp.failure('Backup schedule not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const now = new Date(); await db.update(databaseBackupSchedules).set({ deletedAt: now, deleteReason: 'Removed by workspace user.', isEnabled: false, updatedAt: now }).where(eq(databaseBackupSchedules.id, schedule.id)); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_schedule_removed', resourceType: 'database_backup_schedule', resourceId: schedule.id, metadata: { workspacePublicId, databaseId }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Database backup schedule removed.'); } catch (error) { return authenticationFailureResponse(error) ?? resp.failure('Backup schedule not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); }
	}

	public static async verify(request: Request, workspacePublicId: number, databaseId: string, backupId: string, metadata: RequestMetadata): Promise<Response> {
		try { const workspace = await workspaceAccess(request, workspacePublicId, metadata); const [backup] = await db.select().from(databaseBackups).where(and(eq(databaseBackups.id, backupId), eq(databaseBackups.workspaceId, workspace.id), eq(databaseBackups.logicalDatabaseId, databaseId), eq(databaseBackups.status, 'completed'), isNull(databaseBackups.deletedAt))).limit(1); if (!backup?.storageKey || !backup.checksumSha256) return resp.failure('Backup not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await db.update(databaseBackups).set({ verificationStatus: 'running', verificationFailureReason: null, updatedAt: new Date() }).where(eq(databaseBackups.id, backup.id)); try { await databaseBackupService.verify(backup.storageKey, backup.checksumSha256, backup.storageProvider); } catch (error) { await db.update(databaseBackups).set({ verificationStatus: 'failed', verificationFailureReason: error instanceof Error ? error.message : 'Verification failed.', updatedAt: new Date() }).where(eq(databaseBackups.id, backup.id)); throw error; } const verifiedAt = new Date(); await db.update(databaseBackups).set({ verificationStatus: 'verified', lastVerifiedAt: verifiedAt, updatedAt: verifiedAt }).where(eq(databaseBackups.id, backup.id)); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_verified', resourceType: 'database_backup', resourceId: backup.id, metadata: { workspacePublicId, databaseId, checksumSha256: backup.checksumSha256 }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Backup integrity verified.', { id: backup.id, verifiedAt }, resp.codes.UPDATED); } catch (error) { return authenticationFailureResponse(error) ?? resp.failure(error instanceof Error ? error.message : 'Backup verification failed.', resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}

	public static async clone(request: Request, workspacePublicId: number, databaseId: string, backupId: string, input: CloneDatabaseBackupRequest, metadata: RequestMetadata): Promise<Response> {
		try { const workspace = await workspaceAccess(request, workspacePublicId, metadata); const [source, target] = await Promise.all([databaseRecord(workspace.id, databaseId), databaseRecord(workspace.id, input.targetDatabaseId)]); if (!source || !target || target.database.id === source.database.id) return resp.failure('Clone target database not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); if (source.cluster.engine !== target.cluster.engine) return resp.failure('Clone target must use the same database engine.', resp.codes.ORDER_CANNOT_BE_PROCESSED, undefined, null, undefined, 422); if (input.confirmation !== target.database.databaseName) return resp.failure('Confirmation must exactly match the target database name.', resp.codes.VALIDATION_ERROR, [{ field: 'confirmation', message: 'Target database name does not match.' }], null, undefined, 400); const [backup] = await db.select().from(databaseBackups).where(and(eq(databaseBackups.id, backupId), eq(databaseBackups.workspaceId, workspace.id), eq(databaseBackups.logicalDatabaseId, source.database.id), eq(databaseBackups.status, 'completed'), isNull(databaseBackups.deletedAt))).limit(1); if (!backup?.storageKey || !backup.checksumSha256) return resp.failure('Backup not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await databaseBackupService.restore(connection(target), backup.storageKey, backup.checksumSha256, backup.storageProvider); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_cloned', resourceType: 'database_backup', resourceId: backup.id, metadata: { workspacePublicId, sourceDatabaseId: databaseId, targetDatabaseId: input.targetDatabaseId }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Backup cloned to target database.', { backupId, targetDatabaseId: input.targetDatabaseId }, resp.codes.UPDATED); } catch (error) { return authenticationFailureResponse(error) ?? resp.failure(error instanceof Error ? error.message : 'Backup clone failed.', resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}

	public static async delete(request: Request, workspacePublicId: number, databaseId: string, backupId: string, input: DestructiveActionRequest, metadata: RequestMetadata): Promise<Response> {
		try { const workspace = await workspaceAccess(request, workspacePublicId, metadata); const [backup] = await db.select().from(databaseBackups).where(and(eq(databaseBackups.id, backupId), eq(databaseBackups.workspaceId, workspace.id), eq(databaseBackups.logicalDatabaseId, databaseId), isNull(databaseBackups.deletedAt))).limit(1); if (!backup) return resp.failure('Backup not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const confirmationName = `backup-${backup.id.slice(0, 8)}`; if (input.confirmationName !== confirmationName || input.connectedResourceNames.length) { await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_delete_rejected', resourceType: 'database_backup', resourceId: backup.id, metadata: { workspacePublicId, databaseId, reason: 'Confirmation mismatch.' }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.failure('Backup deletion confirmation does not match.', resp.codes.ORDER_CANNOT_BE_PROCESSED, undefined, null, undefined, 422); } if (backup.storageKey) await databaseBackupService.delete(backup.storageKey, backup.storageProvider); const deletedAt = new Date(); await db.update(databaseBackups).set({ status: 'deleted', deletedAt, deleteReason: 'Deleted by workspace user.', updatedAt: deletedAt }).where(eq(databaseBackups.id, backup.id)); await recordAuditLog({ actorUserId: workspace.actorUserId, action: 'logical_database.backup_deleted', resourceType: 'database_backup', resourceId: backup.id, metadata: { workspacePublicId, databaseId }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Database backup deleted.', { id: backup.id }, resp.codes.UPDATED); }
		catch (error) { return authenticationFailureResponse(error) ?? resp.failure(error instanceof Error ? error.message : 'Backup deletion failed.', resp.codes.INTERNAL_SERVICE_ERROR, undefined, null, undefined, 500); }
	}
}
