import { and, eq, isNull } from 'drizzle-orm';
import { resp } from '@qubitcodes/qcresp';

import { db } from '@db/client';
import { dnsProviderConnections } from '@db/schema';
import type { DnsProviderCode, SaveDnsProviderInput } from '@schemas/dnsProvider';
import { recordAuditLog } from '@services/auditLogService';
import { authorizeAdmin } from '@services/authorization/adminAuthorizationService';
import { saveDnsProviderCredential, validateDnsProviderCredential } from '@services/domains/dnsProviderCredentialService';
import type { RequestMetadata } from '@utils/request';

const publicProjection = { accountIdentifier: dnsProviderConnections.accountIdentifier, lastError: dnsProviderConnections.lastError, lastValidatedAt: dnsProviderConnections.lastValidatedAt, provider: dnsProviderConnections.provider, status: dnsProviderConnections.status, tokenSuffix: dnsProviderConnections.tokenSuffix, updatedAt: dnsProviderConnections.updatedAt };

/** Admin-only lifecycle for encrypted platform DNS-provider credentials. */
export class DnsProviderController {
	public static async index(request: Request, metadata: RequestMetadata): Promise<Response> { try { await authorizeAdmin(request, 'platform_settings.view', metadata); const records = await db.select(publicProjection).from(dnsProviderConnections).where(isNull(dnsProviderConnections.deletedAt)); return resp.success('DNS provider connections retrieved.', records); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
	public static async save(request: Request, provider: DnsProviderCode, input: SaveDnsProviderInput, metadata: RequestMetadata): Promise<Response> { try { const admin = await authorizeAdmin(request, 'platform_settings.update', metadata); await saveDnsProviderCredential(provider, input, admin.userId); await recordAuditLog({ action: 'dns_provider.saved', actorUserId: admin.userId, resourceType: 'dns_provider_connection', metadata: { provider, rotated: Boolean(input.token) }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('DNS provider connection saved.', null, resp.codes.UPDATED); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Unable to save DNS provider.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); } }
	public static async validate(request: Request, provider: DnsProviderCode, metadata: RequestMetadata): Promise<Response> { let admin: Awaited<ReturnType<typeof authorizeAdmin>>; try { admin = await authorizeAdmin(request, 'platform_settings.update', metadata); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } try { await validateDnsProviderCredential(provider); await db.update(dnsProviderConnections).set({ status: 'active', lastValidatedAt: new Date(), lastError: null, updatedAt: new Date() }).where(and(eq(dnsProviderConnections.provider, provider), isNull(dnsProviderConnections.deletedAt))); await recordAuditLog({ action: 'dns_provider.validated', actorUserId: admin.userId, resourceType: 'dns_provider_connection', metadata: { provider }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('DNS provider connection validated.'); } catch (error) { const message = error instanceof Error ? error.message : 'Unable to validate DNS provider.'; await db.update(dnsProviderConnections).set({ status: 'unhealthy', lastError: message.slice(0, 500), updatedAt: new Date() }).where(and(eq(dnsProviderConnections.provider, provider), isNull(dnsProviderConnections.deletedAt))); return resp.failure(message, resp.codes.EXTERNAL_SERVICE_ERROR, undefined, null, undefined, 502); } }
	public static async remove(request: Request, provider: DnsProviderCode, metadata: RequestMetadata): Promise<Response> { try { const admin = await authorizeAdmin(request, 'platform_settings.update', metadata); await db.update(dnsProviderConnections).set({ deletedAt: new Date(), deleteReason: 'Removed from platform settings.', status: 'disabled', updatedByUserId: admin.userId, updatedAt: new Date() }).where(and(eq(dnsProviderConnections.provider, provider), isNull(dnsProviderConnections.deletedAt))); await recordAuditLog({ action: 'dns_provider.removed', actorUserId: admin.userId, resourceType: 'dns_provider_connection', metadata: { provider }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('DNS provider connection removed.'); } catch { return resp.failure('Unable to remove DNS provider.', resp.codes.GENERAL_SERVER_ERROR, undefined, null, undefined, 500); } }
}
