import { and, asc, eq, isNull, ne } from 'drizzle-orm';
import { resp } from '@qubitcodes/qcresp';
import { db } from '@db/client';
import { applicationBuilds, runtimeImages } from '@db/schema';
import type { CreateRuntimeImageInput, UpdateRuntimeImageInput } from '@schemas/runtimeImage';
import { recordAuditLog } from '@services/auditLogService';
import { authorizeAdmin } from '@services/authorization/adminAuthorizationService';
import type { RequestMetadata } from '@utils/request';

const publicFields = { code: runtimeImages.code, createdAt: runtimeImages.createdAt, defaultPort: runtimeImages.defaultPort, digest: runtimeImages.digest, id: runtimeImages.id, isDefault: runtimeImages.isDefault, language: runtimeImages.language, metadata: runtimeImages.metadata, registry: runtimeImages.registry, repository: runtimeImages.repository, status: runtimeImages.status, tag: runtimeImages.tag, updatedAt: runtimeImages.updatedAt, version: runtimeImages.version };
export class RuntimeImageController {
	public static async index(request: Request, metadata: RequestMetadata): Promise<Response> { try { await authorizeAdmin(request, 'provisioning.view', metadata); return resp.success('Runtime images retrieved.', await db.select(publicFields).from(runtimeImages).where(isNull(runtimeImages.deletedAt)).orderBy(asc(runtimeImages.language), asc(runtimeImages.version))); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
	public static async create(request: Request, input: CreateRuntimeImageInput, metadata: RequestMetadata): Promise<Response> { try { const admin = await authorizeAdmin(request, 'provisioning.create', metadata); const [row] = await db.transaction(async (transaction) => { if (input.isDefault) await transaction.update(runtimeImages).set({ isDefault: false, updatedAt: new Date() }).where(and(eq(runtimeImages.language, input.language), isNull(runtimeImages.deletedAt))); return transaction.insert(runtimeImages).values(input).returning(publicFields); }); await recordAuditLog({ action: 'runtime_image.created', actorUserId: admin.userId, ipAddress: metadata.ipAddress, metadata: { code: row.code }, resourceId: row.id, resourceType: 'runtime_image', userAgent: metadata.userAgent }); return resp.success('Runtime image created.', row, resp.codes.CREATED, undefined, 201); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Runtime image creation failed.', resp.codes.INVALID_INPUT_DATA, undefined, null, undefined, 400); } }
	public static async update(request: Request, imageId: string, input: UpdateRuntimeImageInput, metadata: RequestMetadata): Promise<Response> { try { const admin = await authorizeAdmin(request, 'provisioning.update', metadata); const [current] = await db.select().from(runtimeImages).where(and(eq(runtimeImages.id, imageId), isNull(runtimeImages.deletedAt))).limit(1); if (!current) return resp.failure('Runtime image not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const language = input.language ?? current.language; const [row] = await db.transaction(async (transaction) => { if (input.isDefault) await transaction.update(runtimeImages).set({ isDefault: false, updatedAt: new Date() }).where(and(eq(runtimeImages.language, language), ne(runtimeImages.id, imageId), isNull(runtimeImages.deletedAt))); return transaction.update(runtimeImages).set({ ...input, isDefault: input.status && input.status !== 'active' ? false : input.isDefault, updatedAt: new Date() }).where(eq(runtimeImages.id, imageId)).returning(publicFields); }); await recordAuditLog({ action: 'runtime_image.updated', actorUserId: admin.userId, ipAddress: metadata.ipAddress, metadata: { changedFields: Object.keys(input), code: row.code }, resourceId: row.id, resourceType: 'runtime_image', userAgent: metadata.userAgent }); return resp.success('Runtime image updated.', row, resp.codes.UPDATED); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Runtime image update failed.', resp.codes.INVALID_INPUT_DATA, undefined, null, undefined, 400); } }
	public static async destroy(request: Request, imageId: string, reason: string, metadata: RequestMetadata): Promise<Response> { try { const admin = await authorizeAdmin(request, 'provisioning.update', metadata); const [inUse] = await db.select({ id: applicationBuilds.id }).from(applicationBuilds).where(and(eq(applicationBuilds.runtimeImageId, imageId), isNull(applicationBuilds.deletedAt))).limit(1); if (inUse) return resp.failure('Runtime image has build history; disable it instead.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); const [row] = await db.update(runtimeImages).set({ deleteReason: reason, deletedAt: new Date(), isDefault: false, status: 'disabled', updatedAt: new Date() }).where(and(eq(runtimeImages.id, imageId), isNull(runtimeImages.deletedAt))).returning({ code: runtimeImages.code, id: runtimeImages.id }); if (!row) return resp.failure('Runtime image not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await recordAuditLog({ action: 'runtime_image.deleted', actorUserId: admin.userId, ipAddress: metadata.ipAddress, metadata: { code: row.code, reason }, resourceId: row.id, resourceType: 'runtime_image', userAgent: metadata.userAgent }); return resp.success('Runtime image deleted.', row); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Runtime image deletion failed.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
}
