import { and, desc, eq, isNull } from 'drizzle-orm';
import { resp } from '@qubitcodes/qcresp';

import { db } from '@db/client';
import { customers, packages, users, workspaceMemberships, workspaces, workspaceSubscriptionItems, workspaceSubscriptions } from '@db/schema';
import type { z } from 'zod';
import type { subscriptionAddOnCancellationSchema, subscriptionAddOnSchema, subscriptionLifecycleSchema } from '@schemas/subscriptionAdministration';
import { recordAuditLog } from '@services/auditLogService';
import { authorizeAdmin } from '@services/authorization/adminAuthorizationService';
import type { RequestMetadata } from '@utils/request';

type LifecycleInput = z.infer<typeof subscriptionLifecycleSchema>;
type AddOnInput = z.infer<typeof subscriptionAddOnSchema>;
type CancelAddOnInput = z.infer<typeof subscriptionAddOnCancellationSchema>;

const projection = { workspaceId: workspaces.id, workspacePublicId: workspaces.publicId, workspaceName: workspaces.name, workspaceType: workspaces.type, workspaceStatus: workspaces.status, customerPublicId: customers.publicId, ownerUserPublicId: users.publicId, ownerName: users.displayName, ownerCountryCode: users.countryCode, ownerMobile: users.mobile, subscriptionId: workspaceSubscriptions.id, subscriptionStatus: workspaceSubscriptions.status, cancelAtPeriodEnd: workspaceSubscriptions.cancelAtPeriodEnd, termEndsAt: workspaceSubscriptions.termEndsAt, packageName: packages.name };

/** Permission-gated administration of customers, workspaces, primary subscriptions, and add-ons. */
export class SubscriptionAdministrationController {
	public static async index(request: Request, metadata: RequestMetadata): Promise<Response> { try { await authorizeAdmin(request, 'subscriptions.view', metadata); const rows = await db.select(projection).from(workspaces).leftJoin(workspaceMemberships, and(eq(workspaceMemberships.workspaceId, workspaces.id), eq(workspaceMemberships.role, 'owner'), eq(workspaceMemberships.status, 'active'), isNull(workspaceMemberships.deletedAt))).leftJoin(customers, and(eq(customers.id, workspaceMemberships.customerId), isNull(customers.deletedAt))).leftJoin(users, and(eq(users.id, customers.userId), isNull(users.deletedAt))).leftJoin(workspaceSubscriptions, and(eq(workspaceSubscriptions.workspaceId, workspaces.id), eq(workspaceSubscriptions.isPrimary, true), isNull(workspaceSubscriptions.deletedAt))).leftJoin(packages, eq(packages.id, workspaceSubscriptions.packageId)).where(isNull(workspaces.deletedAt)).orderBy(desc(workspaces.createdAt)); return resp.success('Customer workspaces retrieved.', rows); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
	public static async show(request: Request, publicId: number, metadata: RequestMetadata): Promise<Response> { try { await authorizeAdmin(request, 'subscriptions.view', metadata); const [workspace] = await db.select(projection).from(workspaces).leftJoin(workspaceMemberships, and(eq(workspaceMemberships.workspaceId, workspaces.id), eq(workspaceMemberships.role, 'owner'), eq(workspaceMemberships.status, 'active'), isNull(workspaceMemberships.deletedAt))).leftJoin(customers, eq(customers.id, workspaceMemberships.customerId)).leftJoin(users, eq(users.id, customers.userId)).leftJoin(workspaceSubscriptions, and(eq(workspaceSubscriptions.workspaceId, workspaces.id), eq(workspaceSubscriptions.isPrimary, true), isNull(workspaceSubscriptions.deletedAt))).leftJoin(packages, eq(packages.id, workspaceSubscriptions.packageId)).where(and(eq(workspaces.publicId, publicId), isNull(workspaces.deletedAt))).orderBy(desc(workspaceSubscriptions.createdAt)).limit(1); if (!workspace) return resp.failure('Workspace not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const items = workspace.subscriptionId ? await db.select().from(workspaceSubscriptionItems).where(and(eq(workspaceSubscriptionItems.subscriptionId, workspace.subscriptionId), isNull(workspaceSubscriptionItems.deletedAt))).orderBy(desc(workspaceSubscriptionItems.createdAt)) : []; return resp.success('Customer workspace retrieved.', { ...workspace, items }); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
	public static async lifecycle(request: Request, publicId: number, input: LifecycleInput, metadata: RequestMetadata): Promise<Response> { try { const actor = await authorizeAdmin(request, 'subscriptions.update', metadata); const now = new Date(); const [subscription] = await db.update(workspaceSubscriptions).set({ status: input.status, cancelledAt: input.status === 'cancelled' ? now : null, cancellationReason: input.status === 'cancelled' ? input.reason ?? 'Cancelled by administrator.' : null, cancelAtPeriodEnd: false, updatedAt: now }).where(and(eq(workspaceSubscriptions.workspaceId, db.select({ id: workspaces.id }).from(workspaces).where(and(eq(workspaces.publicId, publicId), isNull(workspaces.deletedAt)))), eq(workspaceSubscriptions.isPrimary, true), isNull(workspaceSubscriptions.deletedAt))).returning({ id: workspaceSubscriptions.id, status: workspaceSubscriptions.status }); if (!subscription) return resp.failure('Primary subscription not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await recordAuditLog({ actorUserId: actor.userId, action: `subscription.admin_${input.status}`, resourceType: 'workspace_subscription', resourceId: subscription.id, metadata: { workspacePublicId: publicId, reason: input.reason }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Subscription lifecycle updated.', subscription, resp.codes.UPDATED); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Subscription update failed.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); } }
	public static async addOn(request: Request, publicId: number, input: AddOnInput, metadata: RequestMetadata): Promise<Response> { try { const actor = await authorizeAdmin(request, 'subscriptions.update', metadata); const [subscription] = await db.select({ id: workspaceSubscriptions.id }).from(workspaceSubscriptions).innerJoin(workspaces, eq(workspaces.id, workspaceSubscriptions.workspaceId)).where(and(eq(workspaces.publicId, publicId), eq(workspaceSubscriptions.isPrimary, true), eq(workspaceSubscriptions.status, 'active'), isNull(workspaceSubscriptions.deletedAt), isNull(workspaces.deletedAt))).limit(1); if (!subscription) return resp.failure('Active primary subscription not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const [item] = await db.insert(workspaceSubscriptionItems).values({ subscriptionId: subscription.id, code: input.code, nameSnapshot: input.name, quantity: input.quantity, unitAmountMinor: input.unitAmountMinor, currency: input.currency, entitlementSnapshot: input.entitlementSnapshot }).returning(); if (!item) throw new Error('Unable to add subscription item.'); await recordAuditLog({ actorUserId: actor.userId, action: 'subscription.add_on_created', resourceType: 'workspace_subscription_item', resourceId: item.id, metadata: { workspacePublicId: publicId, code: item.code, quantity: item.quantity }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Subscription add-on created.', item, resp.codes.CREATED, undefined, 201); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Add-on creation failed.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); } }
	public static async cancelAddOn(request: Request, publicId: number, itemId: string, input: CancelAddOnInput, metadata: RequestMetadata): Promise<Response> { try { const actor = await authorizeAdmin(request, 'subscriptions.update', metadata); const now = new Date(); const [item] = await db.update(workspaceSubscriptionItems).set({ status: 'cancelled', endsAt: now, updatedAt: now }).where(and(eq(workspaceSubscriptionItems.id, itemId), eq(workspaceSubscriptionItems.status, 'active'), isNull(workspaceSubscriptionItems.deletedAt), eq(workspaceSubscriptionItems.subscriptionId, db.select({ id: workspaceSubscriptions.id }).from(workspaceSubscriptions).innerJoin(workspaces, eq(workspaces.id, workspaceSubscriptions.workspaceId)).where(and(eq(workspaces.publicId, publicId), eq(workspaceSubscriptions.isPrimary, true), isNull(workspaceSubscriptions.deletedAt)))))).returning({ id: workspaceSubscriptionItems.id }); if (!item) return resp.failure('Active add-on not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await recordAuditLog({ actorUserId: actor.userId, action: 'subscription.add_on_cancelled', resourceType: 'workspace_subscription_item', resourceId: item.id, metadata: { workspacePublicId: publicId, reason: input.reason }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Subscription add-on cancelled.', item, resp.codes.UPDATED); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Add-on cancellation failed.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); } }
}
