import { and, count, desc, eq, isNull, sql } from 'drizzle-orm';
import { resp } from '@qubitcodes/qcresp';

import { db } from '@db/client';
import { applicationBuilds, customers, logicalDatabases, workspaceEntitlementOverrides, workspaceMemberships, workspaces, workspaceSubscriptions, workspaceUsageObservations, workspaceUsageReservations } from '@db/schema';
import type { z } from 'zod';
import type { revokeUsageOverrideSchema, usageObservationSchema, usageOverrideSchema } from '@schemas/usage';
import { recordAuditLog } from '@services/auditLogService';
import { authenticateSession } from '@services/auth/authenticatedSessionService';
import { authorizeAdmin } from '@services/authorization/adminAuthorizationService';
import { effectiveEntitlement, recordUsageObservation } from '@services/usage/quotaEngine';
import type { RequestMetadata } from '@utils/request';

type OverrideInput = z.infer<typeof usageOverrideSchema>; type RevokeInput = z.infer<typeof revokeUsageOverrideSchema>; type ObservationInput = z.infer<typeof usageObservationSchema>;

async function workspaceByPublicId(publicId: number): Promise<{ id: string; publicId: number } | undefined> { const [row] = await db.select({ id: workspaces.id, publicId: workspaces.publicId }).from(workspaces).where(and(eq(workspaces.publicId, publicId), isNull(workspaces.deletedAt))).limit(1); return row; }
async function customerWorkspace(request: Request, publicId: number, metadata: RequestMetadata) { const actor = await authenticateSession(request, metadata); const [row] = await db.select({ id: workspaces.id, publicId: workspaces.publicId }).from(customers).innerJoin(workspaceMemberships, and(eq(workspaceMemberships.customerId, customers.id), eq(workspaceMemberships.status, 'active'), isNull(workspaceMemberships.deletedAt))).innerJoin(workspaces, and(eq(workspaces.id, workspaceMemberships.workspaceId), eq(workspaces.publicId, publicId), isNull(workspaces.deletedAt))).where(and(eq(customers.userId, actor.userId), isNull(customers.deletedAt))).limit(1); if (!row) throw new Error('Workspace not found.'); return { ...row, actorUserId: actor.userId }; }

async function summary(workspaceId: string) {
	const [subscription] = await db.select({ snapshot: workspaceSubscriptions.entitlementSnapshot }).from(workspaceSubscriptions).where(and(eq(workspaceSubscriptions.workspaceId, workspaceId), eq(workspaceSubscriptions.isPrimary, true), sql`${workspaceSubscriptions.status} IN ('active','trialing')`, isNull(workspaceSubscriptions.deletedAt))).orderBy(desc(workspaceSubscriptions.createdAt)).limit(1);
	if (!subscription) throw new Error('Active subscription not found.');
	const [overrideRows, observations, [{ applications }], [{ databases }], reservations] = await Promise.all([
		db.select().from(workspaceEntitlementOverrides).where(and(eq(workspaceEntitlementOverrides.workspaceId, workspaceId), isNull(workspaceEntitlementOverrides.deletedAt))).orderBy(desc(workspaceEntitlementOverrides.createdAt)),
		db.select().from(workspaceUsageObservations).where(and(eq(workspaceUsageObservations.workspaceId, workspaceId), isNull(workspaceUsageObservations.deletedAt))).orderBy(desc(workspaceUsageObservations.observedAt)),
		db.select({ applications: count() }).from(applicationBuilds).where(and(eq(applicationBuilds.workspaceId, workspaceId), isNull(applicationBuilds.deletedAt))),
		db.select({ databases: count() }).from(logicalDatabases).where(and(eq(logicalDatabases.workspaceId, workspaceId), isNull(logicalDatabases.deletedAt))),
		db.select({ code: workspaceUsageReservations.entitlementCode, quantity: workspaceUsageReservations.quantity, status: workspaceUsageReservations.status, expiresAt: workspaceUsageReservations.expiresAt }).from(workspaceUsageReservations).where(and(eq(workspaceUsageReservations.workspaceId, workspaceId), eq(workspaceUsageReservations.status, 'pending'), isNull(workspaceUsageReservations.deletedAt))),
	]);
	const codes = [...new Set([...subscription.snapshot.filter((item) => item.isCustomerVisible !== false).map((item) => String(item.code)), ...overrideRows.filter((item) => !item.revokedAt).map((item) => item.entitlementCode)])];
	const latest = new Map<string, typeof observations[number]>(); for (const observation of observations) if (!latest.has(observation.entitlementCode)) latest.set(observation.entitlementCode, observation);
	const usage = await Promise.all(codes.map(async (code) => { const entitlement = await effectiveEntitlement(workspaceId, code); const observation = latest.get(code); const current = code === 'applications.count' ? Number(applications) : code === 'databases.count' ? Number(databases) : observation?.value ?? 0; return { code, current, limit: entitlement.isUnlimited ? null : entitlement.limit, unlimited: entitlement.isUnlimited, mode: entitlement.mode, booleanValue: entitlement.booleanValue, pending: reservations.filter((item) => item.code === code && item.expiresAt > new Date()).reduce((total, item) => total + item.quantity, 0), observation: observation ? { value: observation.value, unit: observation.unit, source: observation.source, observedAt: observation.observedAt, staleAfter: observation.staleAfter, status: observation.staleAfter <= new Date() ? 'stale' : observation.status } : null }; }));
	return { usage, overrides: overrideRows, generatedAt: new Date() };
}

/** Customer-visible usage freshness and permission-gated administrative override operations. */
export class UsageController {
	public static async customer(request: Request, publicId: number, metadata: RequestMetadata): Promise<Response> { try { const workspace = await customerWorkspace(request, publicId, metadata); return resp.success('Workspace usage retrieved.', await summary(workspace.id)); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Usage unavailable.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); } }
	public static async admin(request: Request, publicId: number, metadata: RequestMetadata): Promise<Response> { try { await authorizeAdmin(request, 'usage.view', metadata); const workspace = await workspaceByPublicId(publicId); if (!workspace) return resp.failure('Workspace not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); return resp.success('Workspace usage retrieved.', await summary(workspace.id)); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
	public static async override(request: Request, publicId: number, input: OverrideInput, metadata: RequestMetadata): Promise<Response> { try { const actor = await authorizeAdmin(request, 'usage.update', metadata); const workspace = await workspaceByPublicId(publicId); if (!workspace) return resp.failure('Workspace not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const row = await db.transaction(async (transaction) => { await transaction.update(workspaceEntitlementOverrides).set({ revokedAt: new Date(), revokedByUserId: actor.userId, revokeReason: 'Superseded by a new override.', updatedAt: new Date() }).where(and(eq(workspaceEntitlementOverrides.workspaceId, workspace.id), eq(workspaceEntitlementOverrides.entitlementCode, input.entitlementCode), isNull(workspaceEntitlementOverrides.revokedAt), isNull(workspaceEntitlementOverrides.deletedAt))); const [created] = await transaction.insert(workspaceEntitlementOverrides).values({ workspaceId: workspace.id, entitlementCode: input.entitlementCode, enforcementMode: input.enforcementMode, numericValue: input.numericValue, booleanValue: input.booleanValue, isUnlimited: input.isUnlimited, reason: input.reason, expiresAt: input.expiresAt ? new Date(input.expiresAt) : undefined, createdByUserId: actor.userId }).returning(); return created; }); if (!row) throw new Error('Unable to create override.'); await recordAuditLog({ actorUserId: actor.userId, action: 'usage.override_created', resourceType: 'workspace_entitlement_override', resourceId: row.id, metadata: { workspacePublicId: publicId, entitlementCode: input.entitlementCode, reason: input.reason }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Workspace entitlement override created.', row, resp.codes.CREATED, undefined, 201); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Override failed.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); } }
	public static async revoke(request: Request, publicId: number, overrideId: string, input: RevokeInput, metadata: RequestMetadata): Promise<Response> { try { const actor = await authorizeAdmin(request, 'usage.update', metadata); const workspace = await workspaceByPublicId(publicId); if (!workspace) return resp.failure('Workspace not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const [row] = await db.update(workspaceEntitlementOverrides).set({ revokedAt: new Date(), revokedByUserId: actor.userId, revokeReason: input.reason, updatedAt: new Date() }).where(and(eq(workspaceEntitlementOverrides.id, overrideId), eq(workspaceEntitlementOverrides.workspaceId, workspace.id), isNull(workspaceEntitlementOverrides.revokedAt), isNull(workspaceEntitlementOverrides.deletedAt))).returning({ id: workspaceEntitlementOverrides.id }); if (!row) return resp.failure('Active override not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); await recordAuditLog({ actorUserId: actor.userId, action: 'usage.override_revoked', resourceType: 'workspace_entitlement_override', resourceId: row.id, metadata: { workspacePublicId: publicId, reason: input.reason }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Workspace entitlement override revoked.', row, resp.codes.UPDATED); } catch { return resp.failure('Permission denied.', resp.codes.PERMISSION_DENIED, undefined, null, undefined, 403); } }
	public static async observation(request: Request, publicId: number, input: ObservationInput, metadata: RequestMetadata): Promise<Response> { try { const actor = await authorizeAdmin(request, 'usage.update', metadata); const workspace = await workspaceByPublicId(publicId); if (!workspace) return resp.failure('Workspace not found.', resp.codes.RESOURCE_NOT_FOUND, undefined, null, undefined, 404); const id = await recordUsageObservation({ workspaceId: workspace.id, code: input.entitlementCode, value: input.value, unit: input.unit, source: input.source, observedAt: input.observedAt ? new Date(input.observedAt) : undefined, staleAfter: new Date(input.staleAfter), periodStart: input.periodStart ? new Date(input.periodStart) : undefined, periodEnd: input.periodEnd ? new Date(input.periodEnd) : undefined, metadata: input.metadata }); await recordAuditLog({ actorUserId: actor.userId, action: 'usage.observation_recorded', resourceType: 'workspace_usage_observation', resourceId: id, metadata: { workspacePublicId: publicId, entitlementCode: input.entitlementCode, source: input.source }, ipAddress: metadata.ipAddress, userAgent: metadata.userAgent }); return resp.success('Usage observation recorded.', { id }, resp.codes.CREATED, undefined, 201); } catch (error) { return resp.failure(error instanceof Error ? error.message : 'Observation failed.', resp.codes.GENERAL_BUSINESS_LOGIC_ERROR, undefined, null, undefined, 422); } }
}
