import { AlertTriangle, LoaderCircle } from 'lucide-react';
import { type FormEvent, useMemo, useState } from 'react';

interface DestructiveConfirmationValue { acceptedImpact: boolean; confirmationName: string; connectedResourceNames: string[] }
interface DestructiveConfirmationProps { busy?: boolean; connectedResourceLabel?: string; connectedResourceNames?: string[]; description: string; onCancel: () => void; onConfirm: (value: DestructiveConfirmationValue) => Promise<void> | void; resourceName: string; title: string }

/** Shared typed confirmation dialog for irreversible resource deletion. */
export function DestructiveConfirmation({ busy = false, connectedResourceLabel = 'dependent resource', connectedResourceNames = [], description, onCancel, onConfirm, resourceName, title }: DestructiveConfirmationProps) {
	const [confirmationName, setConfirmationName] = useState('');
	const [acceptedImpact, setAcceptedImpact] = useState(false);
	const [dependencyConfirmations, setDependencyConfirmations] = useState(() => connectedResourceNames.map(() => ''));
	const dependenciesMatch = useMemo(() => connectedResourceNames.every((name, index) => dependencyConfirmations[index] === name), [connectedResourceNames, dependencyConfirmations]);
	const ready = confirmationName === resourceName && dependenciesMatch && (!connectedResourceNames.length || acceptedImpact);
	async function submit(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (ready && !busy) await onConfirm({ acceptedImpact, confirmationName, connectedResourceNames: [...connectedResourceNames] }); }
	return <div aria-modal="true" className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-black/70 p-4" role="dialog"><form className="my-auto w-full max-w-xl rounded-3xl border border-red-500/20 bg-app-surface p-6 shadow-2xl" onSubmit={(event) => void submit(event)}><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-red-500/10 text-red-600 dark:text-red-300"><AlertTriangle className="size-5" /></span><div><h2 className="text-2xl font-black">{title}</h2><p className="mt-2 text-sm text-app-muted">{description}</p></div></div>{connectedResourceNames.length > 0 && <div className="mt-5 rounded-2xl border border-red-500/20 bg-red-500/5 p-4"><p className="font-bold text-red-700 dark:text-red-300">Currently connected to:</p><ul className="mt-2 list-inside list-disc text-sm">{connectedResourceNames.map((name) => <li key={name}>{name}</li>)}</ul><label className="mt-4 flex items-start gap-3 text-sm font-semibold"><input checked={acceptedImpact} className="mt-0.5 size-4 accent-red-600" onChange={(event) => setAcceptedImpact(event.target.checked)} type="checkbox" /><span>I accept that these {connectedResourceLabel}s may stop working and their configuration will be detached.</span></label></div>}<label className="mt-5 grid gap-2 text-sm font-semibold">Type <strong className="font-mono text-app-text">{resourceName}</strong> to confirm<input autoComplete="off" className="rounded-xl border border-red-500/30 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100" onChange={(event) => setConfirmationName(event.target.value)} value={confirmationName} /></label>{connectedResourceNames.map((name, index) => <label className="mt-4 grid gap-2 text-sm font-semibold" key={`${name}-${index}`}>Type connected {connectedResourceLabel} name <strong className="font-mono text-app-text">{name}</strong><input autoComplete="off" className="rounded-xl border border-red-500/30 bg-white px-4 py-3 text-gray-900 dark:bg-gray-800 dark:text-gray-100" onChange={(event) => setDependencyConfirmations((current) => current.map((value, position) => position === index ? event.target.value : value))} value={dependencyConfirmations[index]} /></label>)}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button className="rounded-xl border border-brand-primary/15 px-4 py-3 font-bold" disabled={busy} onClick={onCancel} type="button">Cancel</button><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40" disabled={!ready || busy} type="submit">{busy && <LoaderCircle className="size-4 animate-spin" />}Delete Permanently</button></div></form></div>;
}
export type { DestructiveConfirmationValue };
