import mysql, { type RowDataPacket } from 'mysql2/promise';
import pg from 'pg';

import type { DatabaseColumnDefinition, DatabaseSchemaMutation } from '@schemas/databaseSchema';
import type { DatabaseExplorerConnection } from '@services/databases/databaseExplorerService';

const postgresIdentifier = (value: string): string => `"${value.replaceAll('"', '""')}"`;
const mysqlIdentifier = (value: string): string => `\`${value.replaceAll('`', '``')}\``;

/** Returns a safely quoted SQL literal for a bounded JSON primitive. */
function sqlLiteral(value: boolean | number | string): string {
	if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
	if (typeof value === 'number') return String(value);
	return `'${value.replaceAll("'", "''")}'`;
}

function columnType(engine: DatabaseExplorerConnection['engine'], column: DatabaseColumnDefinition): string {
	if (engine === 'postgresql') {
		switch (column.type) {
			case 'bigint': return 'BIGINT';
			case 'boolean': return 'BOOLEAN';
			case 'date': return 'DATE';
			case 'decimal': return `NUMERIC(${column.precision ?? 18}, ${column.scale ?? 2})`;
			case 'double': return 'DOUBLE PRECISION';
			case 'integer': return 'INTEGER';
			case 'json': return 'JSONB';
			case 'string': return `VARCHAR(${column.length ?? 255})`;
			case 'text': return 'TEXT';
			case 'timestamp': return 'TIMESTAMP WITH TIME ZONE';
			case 'uuid': return 'UUID';
		}
	}
	switch (column.type) {
		case 'bigint': return 'BIGINT';
		case 'boolean': return 'BOOLEAN';
		case 'date': return 'DATE';
		case 'decimal': return `DECIMAL(${column.precision ?? 18}, ${column.scale ?? 2})`;
		case 'double': return 'DOUBLE';
		case 'integer': return 'INT';
		case 'json': return 'JSON';
		case 'string': return `VARCHAR(${column.length ?? 255})`;
		case 'text': return 'TEXT';
		case 'timestamp': return 'TIMESTAMP';
		case 'uuid': return 'CHAR(36)';
	}
}

function defaultClause(column: DatabaseColumnDefinition): string {
	if (column.default.kind === 'none') return '';
	if (column.default.kind === 'null') return ' DEFAULT NULL';
	if (column.default.kind === 'current_timestamp') return ' DEFAULT CURRENT_TIMESTAMP';
	return ` DEFAULT ${sqlLiteral(column.default.value)}`;
}

function columnSql(engine: DatabaseExplorerConnection['engine'], column: DatabaseColumnDefinition): string {
	const identifier = engine === 'postgresql' ? postgresIdentifier(column.name) : mysqlIdentifier(column.name);
	const identity = column.autoIncrement
		? engine === 'postgresql' ? ' GENERATED BY DEFAULT AS IDENTITY' : ' AUTO_INCREMENT'
		: '';
	return `${identifier} ${columnType(engine, column)}${identity}${column.nullable && !column.primaryKey ? ' NULL' : ' NOT NULL'}${defaultClause(column)}`;
}

const foreignAction = (value: 'cascade' | 'no_action' | 'restrict' | 'set_null'): string => value.replace('_', ' ').toUpperCase();

/** Executes strictly modelled DDL against one tenant-owned logical database. */
export class DatabaseSchemaService {
	public constructor(private readonly connection: DatabaseExplorerConnection) {}

	public async mutate(input: DatabaseSchemaMutation): Promise<{ operation: DatabaseSchemaMutation['operation']; target: string }> {
		this.verifySchemaBoundary(input);
		this.verifyConfirmation(input);
		if (this.connection.engine === 'postgresql') await this.mutatePostgres(input);
		else await this.mutateMysql(input);
		return { operation: input.operation, target: this.target(input) };
	}

	private target(input: DatabaseSchemaMutation): string {
		if (input.operation === 'create_schema' || input.operation === 'rename_schema' || input.operation === 'drop_schema') return input.schema;
		return `${input.schema}.${input.table}`;
	}

	private verifyConfirmation(input: DatabaseSchemaMutation): void {
		if (!('confirmation' in input)) return;
		const expected = input.operation === 'drop_schema'
			? input.schema
			: input.operation === 'drop_column' || input.operation === 'alter_column'
				? `${input.schema}.${input.table}.${input.columnName}`
				: input.operation === 'drop_index'
					? `${input.schema}.${input.table}.${input.indexName}`
					: input.operation === 'drop_constraint'
						? `${input.schema}.${input.table}.${input.constraintName}`
				: `${input.schema}.${input.table}`;
		if (input.confirmation !== expected) throw new Error(`Type ${expected} exactly to confirm this operation.`);
	}

	private verifySchemaBoundary(input: DatabaseSchemaMutation): void {
		const normalized = input.schema.toLowerCase();
		if (normalized === 'information_schema' || normalized === 'pg_catalog' || normalized.startsWith('pg_toast')) throw new Error('System schemas cannot be managed.');
		if ((input.operation === 'drop_schema' || input.operation === 'rename_schema') && normalized === 'public') throw new Error('The default public schema cannot be renamed or removed.');
		if (input.operation === 'add_foreign_key') {
			const reference = input.referenceSchema.toLowerCase();
			if (reference === 'information_schema' || reference === 'pg_catalog' || reference.startsWith('pg_toast')) throw new Error('System schemas cannot be referenced.');
		}
	}

	private postgresClient(): pg.Client {
		return new pg.Client({
			host: this.connection.host,
			port: this.connection.port,
			database: this.connection.databaseName,
			user: this.connection.username,
			password: this.connection.password,
			ssl: this.connection.tlsMode === 'disabled' ? false : { rejectUnauthorized: this.connection.tlsMode === 'verify-full' },
			connectionTimeoutMillis: 10_000,
		});
	}

	private async mysqlClient(): Promise<mysql.Connection> {
		const client = await mysql.createConnection({
			host: this.connection.host,
			port: this.connection.port,
			database: this.connection.databaseName,
			user: this.connection.username,
			password: this.connection.password,
			ssl: this.connection.tlsMode === 'disabled' ? undefined : { rejectUnauthorized: this.connection.tlsMode === 'verify-full' },
			connectTimeout: 10_000,
		});
		await client.query('SET SESSION MAX_EXECUTION_TIME = 15000');
		return client;
	}

	private async mutatePostgres(input: DatabaseSchemaMutation): Promise<void> {
		const client = this.postgresClient();
		await client.connect();
		try {
			await client.query('SET statement_timeout = 15000');
			const schema = postgresIdentifier(input.schema);
			if (input.operation === 'create_schema') await client.query(`CREATE SCHEMA ${schema}`);
			else if (input.operation === 'rename_schema') await client.query(`ALTER SCHEMA ${schema} RENAME TO ${postgresIdentifier(input.newName)}`);
			else if (input.operation === 'drop_schema') await client.query(`DROP SCHEMA ${schema} CASCADE`);
			else {
				const table = `${schema}.${postgresIdentifier(input.table)}`;
				await this.executePostgresTableMutation(client, table, input);
			}
		} finally {
			await client.end();
		}
	}

	private async executePostgresTableMutation(client: pg.Client, table: string, input: Exclude<DatabaseSchemaMutation, { operation: 'create_schema' | 'drop_schema' | 'rename_schema' }>): Promise<void> {
		switch (input.operation) {
			case 'create_table': {
				const primary = input.columns.filter(({ primaryKey }) => primaryKey);
				const definitions = input.columns.map((column) => columnSql('postgresql', column));
				if (primary.length) definitions.push(`PRIMARY KEY (${primary.map(({ name }) => postgresIdentifier(name)).join(', ')})`);
				await client.query(`CREATE TABLE ${table} (${definitions.join(', ')})`);
				return;
			}
			case 'rename_table': await client.query(`ALTER TABLE ${table} RENAME TO ${postgresIdentifier(input.newName)}`); return;
			case 'drop_table': await client.query(`DROP TABLE ${table} CASCADE`); return;
			case 'truncate_table': await client.query(`TRUNCATE TABLE ${table} RESTART IDENTITY CASCADE`); return;
			case 'add_column': await client.query(`ALTER TABLE ${table} ADD COLUMN ${columnSql('postgresql', input.column)}`); return;
			case 'alter_column': {
				if (input.column.autoIncrement) throw new Error('Identity changes are not supported while altering a PostgreSQL column.');
				const oldName = postgresIdentifier(input.columnName);
				const newName = postgresIdentifier(input.column.name);
				if (input.columnName !== input.column.name) await client.query(`ALTER TABLE ${table} RENAME COLUMN ${oldName} TO ${newName}`);
				await client.query(`ALTER TABLE ${table} ALTER COLUMN ${newName} TYPE ${columnType('postgresql', input.column)} USING ${newName}::${columnType('postgresql', input.column)}`);
				await client.query(`ALTER TABLE ${table} ALTER COLUMN ${newName} ${input.column.nullable ? 'DROP' : 'SET'} NOT NULL`);
				if (input.column.default.kind === 'none') await client.query(`ALTER TABLE ${table} ALTER COLUMN ${newName} DROP DEFAULT`);
				else await client.query(`ALTER TABLE ${table} ALTER COLUMN ${newName} SET${defaultClause(input.column)}`);
				return;
			}
			case 'drop_column': await client.query(`ALTER TABLE ${table} DROP COLUMN ${postgresIdentifier(input.columnName)} CASCADE`); return;
			case 'create_index': await client.query(`CREATE ${input.unique ? 'UNIQUE ' : ''}INDEX ${postgresIdentifier(input.indexName)} ON ${table} (${input.columns.map(({ name, direction }) => `${postgresIdentifier(name)} ${direction.toUpperCase()}`).join(', ')})`); return;
			case 'drop_index': await client.query(`DROP INDEX ${postgresIdentifier(input.schema)}.${postgresIdentifier(input.indexName)}`); return;
			case 'add_primary_key': await client.query(`ALTER TABLE ${table} ADD CONSTRAINT ${postgresIdentifier(input.constraintName)} PRIMARY KEY (${input.columns.map(postgresIdentifier).join(', ')})`); return;
			case 'add_foreign_key': await client.query(`ALTER TABLE ${table} ADD CONSTRAINT ${postgresIdentifier(input.constraintName)} FOREIGN KEY (${input.columns.map(postgresIdentifier).join(', ')}) REFERENCES ${postgresIdentifier(input.referenceSchema)}.${postgresIdentifier(input.referenceTable)} (${input.referenceColumns.map(postgresIdentifier).join(', ')}) ON DELETE ${foreignAction(input.onDelete)} ON UPDATE ${foreignAction(input.onUpdate)}`); return;
			case 'drop_constraint': await client.query(`ALTER TABLE ${table} DROP CONSTRAINT ${postgresIdentifier(input.constraintName)}`); return;
		}
	}

	private async mutateMysql(input: DatabaseSchemaMutation): Promise<void> {
		if (input.operation === 'create_schema' || input.operation === 'rename_schema' || input.operation === 'drop_schema') throw new Error('MySQL logical databases cannot manage database-level schemas.');
		if (input.schema !== this.connection.databaseName) throw new Error('Database object not found.');
		const client = await this.mysqlClient();
		try {
			const table = `${mysqlIdentifier(input.schema)}.${mysqlIdentifier(input.table)}`;
			switch (input.operation) {
				case 'create_table': {
					const primary = input.columns.filter(({ primaryKey }) => primaryKey);
					const definitions = input.columns.map((column) => columnSql('mysql', column));
					if (primary.length) definitions.push(`PRIMARY KEY (${primary.map(({ name }) => mysqlIdentifier(name)).join(', ')})`);
					await client.query(`CREATE TABLE ${table} (${definitions.join(', ')}) ENGINE=InnoDB`);
					break;
				}
				case 'rename_table': await client.query(`RENAME TABLE ${table} TO ${mysqlIdentifier(input.schema)}.${mysqlIdentifier(input.newName)}`); break;
				case 'drop_table': await client.query(`DROP TABLE ${table}`); break;
				case 'truncate_table': await client.query(`TRUNCATE TABLE ${table}`); break;
				case 'add_column': await client.query(`ALTER TABLE ${table} ADD COLUMN ${columnSql('mysql', input.column)}`); break;
				case 'alter_column': await client.query(`ALTER TABLE ${table} CHANGE COLUMN ${mysqlIdentifier(input.columnName)} ${columnSql('mysql', input.column)}`); break;
				case 'drop_column': await client.query(`ALTER TABLE ${table} DROP COLUMN ${mysqlIdentifier(input.columnName)}`); break;
				case 'create_index': await client.query(`CREATE ${input.unique ? 'UNIQUE ' : ''}INDEX ${mysqlIdentifier(input.indexName)} ON ${table} (${input.columns.map(({ name, direction }) => `${mysqlIdentifier(name)} ${direction.toUpperCase()}`).join(', ')})`); break;
				case 'drop_index': await client.query(`DROP INDEX ${mysqlIdentifier(input.indexName)} ON ${table}`); break;
				case 'add_primary_key': await client.query(`ALTER TABLE ${table} ADD CONSTRAINT ${mysqlIdentifier(input.constraintName)} PRIMARY KEY (${input.columns.map(mysqlIdentifier).join(', ')})`); break;
				case 'add_foreign_key': await client.query(`ALTER TABLE ${table} ADD CONSTRAINT ${mysqlIdentifier(input.constraintName)} FOREIGN KEY (${input.columns.map(mysqlIdentifier).join(', ')}) REFERENCES ${mysqlIdentifier(input.referenceSchema)}.${mysqlIdentifier(input.referenceTable)} (${input.referenceColumns.map(mysqlIdentifier).join(', ')}) ON DELETE ${foreignAction(input.onDelete)} ON UPDATE ${foreignAction(input.onUpdate)}`); break;
				case 'drop_constraint': {
					const [rows] = await client.query<RowDataPacket[]>('SELECT constraint_type FROM information_schema.table_constraints WHERE constraint_schema = ? AND table_name = ? AND constraint_name = ? LIMIT 1', [input.schema, input.table, input.constraintName]);
					if (!rows[0]) throw new Error('Constraint not found.');
					const type = String(rows[0].constraint_type);
					if (type === 'PRIMARY KEY') await client.query(`ALTER TABLE ${table} DROP PRIMARY KEY`);
					else if (type === 'FOREIGN KEY') await client.query(`ALTER TABLE ${table} DROP FOREIGN KEY ${mysqlIdentifier(input.constraintName)}`);
					else await client.query(`ALTER TABLE ${table} DROP INDEX ${mysqlIdentifier(input.constraintName)}`);
					break;
				}
			}
		} finally {
			await client.end();
		}
	}
}

export const databaseColumnSql = columnSql;
